// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_areas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreateArea = `-- name: AdminCreateArea :one
INSERT INTO areas (slug, name_ar, name_en, region, km_marker, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name_ar, name_en, region, km_marker, sort_order, created_at, updated_at
`

type AdminCreateAreaParams struct {
	Slug      string     `json:"slug"`
	NameAr    string     `json:"name_ar"`
	NameEn    string     `json:"name_en"`
	Region    RegionEnum `json:"region"`
	KmMarker  *int32     `json:"km_marker"`
	SortOrder int32      `json:"sort_order"`
}

func (q *Queries) AdminCreateArea(ctx context.Context, arg AdminCreateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, adminCreateArea,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.Region,
		arg.KmMarker,
		arg.SortOrder,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Region,
		&i.KmMarker,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteArea = `-- name: AdminDeleteArea :execrows
DELETE FROM areas WHERE id = $1
`

func (q *Queries) AdminDeleteArea(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteArea, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetArea = `-- name: AdminGetArea :one
SELECT id, slug, name_ar, name_en, region, km_marker, sort_order, created_at, updated_at FROM areas WHERE id = $1
`

func (q *Queries) AdminGetArea(ctx context.Context, id pgtype.UUID) (Area, error) {
	row := q.db.QueryRow(ctx, adminGetArea, id)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Region,
		&i.KmMarker,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListAreas = `-- name: AdminListAreas :many
SELECT id, slug, name_ar, name_en, region, km_marker, sort_order, created_at, updated_at FROM areas
WHERE ($1::text IS NULL OR slug = $1::text)
ORDER BY sort_order ASC, name_en ASC
`

func (q *Queries) AdminListAreas(ctx context.Context, slug *string) ([]Area, error) {
	rows, err := q.db.Query(ctx, adminListAreas, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Area{}
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.Region,
			&i.KmMarker,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateArea = `-- name: AdminUpdateArea :one
UPDATE areas
SET slug = $1, name_ar = $2, name_en = $3, region = $4,
    km_marker = $5, sort_order = $6
WHERE id = $7
RETURNING id, slug, name_ar, name_en, region, km_marker, sort_order, created_at, updated_at
`

type AdminUpdateAreaParams struct {
	Slug      string      `json:"slug"`
	NameAr    string      `json:"name_ar"`
	NameEn    string      `json:"name_en"`
	Region    RegionEnum  `json:"region"`
	KmMarker  *int32      `json:"km_marker"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateArea(ctx context.Context, arg AdminUpdateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, adminUpdateArea,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.Region,
		arg.KmMarker,
		arg.SortOrder,
		arg.ID,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Region,
		&i.KmMarker,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
