// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreateUnit = `-- name: AdminCreateUnit :one
INSERT INTO units (owner_id, compound_id, slug, title_ar, title_en, description_ar, description_en,
                   house_rules_ar, house_rules_en, type, bedrooms, bathrooms, base_guests, max_guests,
                   area_sqm, floor, sea_distance_m, view, row_number, amenities, lat, lng,
                   exact_address, status)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14,
        $15, $16, $17, $18, $19, $20, $21, $22,
        $23, $24)
RETURNING id, owner_id, compound_id, slug, title_ar, title_en, description_ar, description_en, house_rules_ar, house_rules_en, type, bedrooms, bathrooms, base_guests, max_guests, area_sqm, floor, sea_distance_m, view, row_number, amenities, lat, lng, exact_address, status, created_at, updated_at
`

type AdminCreateUnitParams struct {
	OwnerID       pgtype.UUID    `json:"owner_id"`
	CompoundID    pgtype.UUID    `json:"compound_id"`
	Slug          string         `json:"slug"`
	TitleAr       string         `json:"title_ar"`
	TitleEn       string         `json:"title_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	HouseRulesAr  *string        `json:"house_rules_ar"`
	HouseRulesEn  *string        `json:"house_rules_en"`
	Type          UnitTypeEnum   `json:"type"`
	Bedrooms      int16          `json:"bedrooms"`
	Bathrooms     int16          `json:"bathrooms"`
	BaseGuests    int16          `json:"base_guests"`
	MaxGuests     int16          `json:"max_guests"`
	AreaSqm       *int32         `json:"area_sqm"`
	Floor         *int16         `json:"floor"`
	SeaDistanceM  int32          `json:"sea_distance_m"`
	View          UnitViewEnum   `json:"view"`
	RowNumber     *int16         `json:"row_number"`
	Amenities     []string       `json:"amenities"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	ExactAddress  *string        `json:"exact_address"`
	Status        UnitStatusEnum `json:"status"`
}

func (q *Queries) AdminCreateUnit(ctx context.Context, arg AdminCreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, adminCreateUnit,
		arg.OwnerID,
		arg.CompoundID,
		arg.Slug,
		arg.TitleAr,
		arg.TitleEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.HouseRulesAr,
		arg.HouseRulesEn,
		arg.Type,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.BaseGuests,
		arg.MaxGuests,
		arg.AreaSqm,
		arg.Floor,
		arg.SeaDistanceM,
		arg.View,
		arg.RowNumber,
		arg.Amenities,
		arg.Lat,
		arg.Lng,
		arg.ExactAddress,
		arg.Status,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompoundID,
		&i.Slug,
		&i.TitleAr,
		&i.TitleEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.HouseRulesAr,
		&i.HouseRulesEn,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.BaseGuests,
		&i.MaxGuests,
		&i.AreaSqm,
		&i.Floor,
		&i.SeaDistanceM,
		&i.View,
		&i.RowNumber,
		&i.Amenities,
		&i.Lat,
		&i.Lng,
		&i.ExactAddress,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteUnit = `-- name: AdminDeleteUnit :execrows
DELETE FROM units WHERE id = $1
`

func (q *Queries) AdminDeleteUnit(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetUnit = `-- name: AdminGetUnit :one
SELECT id, owner_id, compound_id, slug, title_ar, title_en, description_ar, description_en, house_rules_ar, house_rules_en, type, bedrooms, bathrooms, base_guests, max_guests, area_sqm, floor, sea_distance_m, view, row_number, amenities, lat, lng, exact_address, status, created_at, updated_at FROM units WHERE id = $1
`

func (q *Queries) AdminGetUnit(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, adminGetUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompoundID,
		&i.Slug,
		&i.TitleAr,
		&i.TitleEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.HouseRulesAr,
		&i.HouseRulesEn,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.BaseGuests,
		&i.MaxGuests,
		&i.AreaSqm,
		&i.Floor,
		&i.SeaDistanceM,
		&i.View,
		&i.RowNumber,
		&i.Amenities,
		&i.Lat,
		&i.Lng,
		&i.ExactAddress,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListUnitImages = `-- name: AdminListUnitImages :many
SELECT id, unit_id, url, alt_ar, alt_en, sort, is_cover, created_at, updated_at FROM unit_images WHERE unit_id = $1 ORDER BY sort ASC, created_at ASC
`

func (q *Queries) AdminListUnitImages(ctx context.Context, unitID pgtype.UUID) ([]UnitImage, error) {
	rows, err := q.db.Query(ctx, adminListUnitImages, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitImage{}
	for rows.Next() {
		var i UnitImage
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Url,
			&i.AltAr,
			&i.AltEn,
			&i.Sort,
			&i.IsCover,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUnits = `-- name: AdminListUnits :many
SELECT u.id, u.slug, u.title_ar, u.title_en, u.type, u.status,
       u.bedrooms, u.max_guests, u.updated_at,
       c.name_en AS compound_name_en, o.name AS owner_name,
       ci.url AS cover_url
FROM units u
JOIN compounds c ON c.id = u.compound_id
JOIN owners    o ON o.id = u.owner_id
LEFT JOIN unit_images ci ON ci.unit_id = u.id AND ci.is_cover
WHERE ($1::text IS NULL OR u.slug = $1::text)
ORDER BY u.updated_at DESC
`

type AdminListUnitsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	TitleAr        string             `json:"title_ar"`
	TitleEn        string             `json:"title_en"`
	Type           UnitTypeEnum       `json:"type"`
	Status         UnitStatusEnum     `json:"status"`
	Bedrooms       int16              `json:"bedrooms"`
	MaxGuests      int16              `json:"max_guests"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompoundNameEn string             `json:"compound_name_en"`
	OwnerName      string             `json:"owner_name"`
	CoverUrl       *string            `json:"cover_url"`
}

// Newest edits first: doubles as the dashboard's "recently edited" list.
func (q *Queries) AdminListUnits(ctx context.Context, slug *string) ([]AdminListUnitsRow, error) {
	rows, err := q.db.Query(ctx, adminListUnits, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUnitsRow{}
	for rows.Next() {
		var i AdminListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleAr,
			&i.TitleEn,
			&i.Type,
			&i.Status,
			&i.Bedrooms,
			&i.MaxGuests,
			&i.UpdatedAt,
			&i.CompoundNameEn,
			&i.OwnerName,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUnit = `-- name: AdminUpdateUnit :one
UPDATE units
SET owner_id = $1, compound_id = $2, slug = $3,
    title_ar = $4, title_en = $5,
    description_ar = $6, description_en = $7,
    house_rules_ar = $8, house_rules_en = $9,
    type = $10, bedrooms = $11, bathrooms = $12,
    base_guests = $13, max_guests = $14,
    area_sqm = $15, floor = $16, sea_distance_m = $17,
    view = $18, row_number = $19, amenities = $20,
    lat = $21, lng = $22, exact_address = $23, status = $24
WHERE id = $25
RETURNING id, owner_id, compound_id, slug, title_ar, title_en, description_ar, description_en, house_rules_ar, house_rules_en, type, bedrooms, bathrooms, base_guests, max_guests, area_sqm, floor, sea_distance_m, view, row_number, amenities, lat, lng, exact_address, status, created_at, updated_at
`

type AdminUpdateUnitParams struct {
	OwnerID       pgtype.UUID    `json:"owner_id"`
	CompoundID    pgtype.UUID    `json:"compound_id"`
	Slug          string         `json:"slug"`
	TitleAr       string         `json:"title_ar"`
	TitleEn       string         `json:"title_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	HouseRulesAr  *string        `json:"house_rules_ar"`
	HouseRulesEn  *string        `json:"house_rules_en"`
	Type          UnitTypeEnum   `json:"type"`
	Bedrooms      int16          `json:"bedrooms"`
	Bathrooms     int16          `json:"bathrooms"`
	BaseGuests    int16          `json:"base_guests"`
	MaxGuests     int16          `json:"max_guests"`
	AreaSqm       *int32         `json:"area_sqm"`
	Floor         *int16         `json:"floor"`
	SeaDistanceM  int32          `json:"sea_distance_m"`
	View          UnitViewEnum   `json:"view"`
	RowNumber     *int16         `json:"row_number"`
	Amenities     []string       `json:"amenities"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	ExactAddress  *string        `json:"exact_address"`
	Status        UnitStatusEnum `json:"status"`
	ID            pgtype.UUID    `json:"id"`
}

func (q *Queries) AdminUpdateUnit(ctx context.Context, arg AdminUpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, adminUpdateUnit,
		arg.OwnerID,
		arg.CompoundID,
		arg.Slug,
		arg.TitleAr,
		arg.TitleEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.HouseRulesAr,
		arg.HouseRulesEn,
		arg.Type,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.BaseGuests,
		arg.MaxGuests,
		arg.AreaSqm,
		arg.Floor,
		arg.SeaDistanceM,
		arg.View,
		arg.RowNumber,
		arg.Amenities,
		arg.Lat,
		arg.Lng,
		arg.ExactAddress,
		arg.Status,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompoundID,
		&i.Slug,
		&i.TitleAr,
		&i.TitleEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.HouseRulesAr,
		&i.HouseRulesEn,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.BaseGuests,
		&i.MaxGuests,
		&i.AreaSqm,
		&i.Floor,
		&i.SeaDistanceM,
		&i.View,
		&i.RowNumber,
		&i.Amenities,
		&i.Lat,
		&i.Lng,
		&i.ExactAddress,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
