// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_compounds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreateCompound = `-- name: AdminCreateCompound :one
INSERT INTO compounds (area_id, slug, name_ar, name_en, description_ar, description_en,
                       amenities, beach_type, gate_info_ar, gate_info_en, lat, lng,
                       cover_image_url, is_featured)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12,
        $13, $14)
RETURNING id, area_id, slug, name_ar, name_en, description_ar, description_en, amenities, beach_type, gate_info_ar, gate_info_en, lat, lng, cover_image_url, is_featured, created_at, updated_at
`

type AdminCreateCompoundParams struct {
	AreaID        pgtype.UUID    `json:"area_id"`
	Slug          string         `json:"slug"`
	NameAr        string         `json:"name_ar"`
	NameEn        string         `json:"name_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	Amenities     []string       `json:"amenities"`
	BeachType     BeachTypeEnum  `json:"beach_type"`
	GateInfoAr    *string        `json:"gate_info_ar"`
	GateInfoEn    *string        `json:"gate_info_en"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	CoverImageUrl *string        `json:"cover_image_url"`
	IsFeatured    bool           `json:"is_featured"`
}

func (q *Queries) AdminCreateCompound(ctx context.Context, arg AdminCreateCompoundParams) (Compound, error) {
	row := q.db.QueryRow(ctx, adminCreateCompound,
		arg.AreaID,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.Amenities,
		arg.BeachType,
		arg.GateInfoAr,
		arg.GateInfoEn,
		arg.Lat,
		arg.Lng,
		arg.CoverImageUrl,
		arg.IsFeatured,
	)
	var i Compound
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.Amenities,
		&i.BeachType,
		&i.GateInfoAr,
		&i.GateInfoEn,
		&i.Lat,
		&i.Lng,
		&i.CoverImageUrl,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteCompound = `-- name: AdminDeleteCompound :execrows
DELETE FROM compounds WHERE id = $1
`

func (q *Queries) AdminDeleteCompound(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteCompound, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetCompound = `-- name: AdminGetCompound :one
SELECT id, area_id, slug, name_ar, name_en, description_ar, description_en, amenities, beach_type, gate_info_ar, gate_info_en, lat, lng, cover_image_url, is_featured, created_at, updated_at FROM compounds WHERE id = $1
`

func (q *Queries) AdminGetCompound(ctx context.Context, id pgtype.UUID) (Compound, error) {
	row := q.db.QueryRow(ctx, adminGetCompound, id)
	var i Compound
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.Amenities,
		&i.BeachType,
		&i.GateInfoAr,
		&i.GateInfoEn,
		&i.Lat,
		&i.Lng,
		&i.CoverImageUrl,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListCompounds = `-- name: AdminListCompounds :many
SELECT c.id, c.area_id, c.slug, c.name_ar, c.name_en, c.description_ar, c.description_en, c.amenities, c.beach_type, c.gate_info_ar, c.gate_info_en, c.lat, c.lng, c.cover_image_url, c.is_featured, c.created_at, c.updated_at, a.name_ar AS area_name_ar, a.name_en AS area_name_en
FROM compounds c
JOIN areas a ON a.id = c.area_id
WHERE ($1::text IS NULL OR c.slug = $1::text)
ORDER BY c.name_en ASC
`

type AdminListCompoundsRow struct {
	ID            pgtype.UUID        `json:"id"`
	AreaID        pgtype.UUID        `json:"area_id"`
	Slug          string             `json:"slug"`
	NameAr        string             `json:"name_ar"`
	NameEn        string             `json:"name_en"`
	DescriptionAr string             `json:"description_ar"`
	DescriptionEn string             `json:"description_en"`
	Amenities     []string           `json:"amenities"`
	BeachType     BeachTypeEnum      `json:"beach_type"`
	GateInfoAr    *string            `json:"gate_info_ar"`
	GateInfoEn    *string            `json:"gate_info_en"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lng           pgtype.Numeric     `json:"lng"`
	CoverImageUrl *string            `json:"cover_image_url"`
	IsFeatured    bool               `json:"is_featured"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AreaNameAr    string             `json:"area_name_ar"`
	AreaNameEn    string             `json:"area_name_en"`
}

func (q *Queries) AdminListCompounds(ctx context.Context, slug *string) ([]AdminListCompoundsRow, error) {
	rows, err := q.db.Query(ctx, adminListCompounds, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCompoundsRow{}
	for rows.Next() {
		var i AdminListCompoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.Amenities,
			&i.BeachType,
			&i.GateInfoAr,
			&i.GateInfoEn,
			&i.Lat,
			&i.Lng,
			&i.CoverImageUrl,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AreaNameAr,
			&i.AreaNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateCompound = `-- name: AdminUpdateCompound :one
UPDATE compounds
SET area_id = $1, slug = $2, name_ar = $3, name_en = $4,
    description_ar = $5, description_en = $6,
    amenities = $7, beach_type = $8,
    gate_info_ar = $9, gate_info_en = $10,
    lat = $11, lng = $12, cover_image_url = $13, is_featured = $14
WHERE id = $15
RETURNING id, area_id, slug, name_ar, name_en, description_ar, description_en, amenities, beach_type, gate_info_ar, gate_info_en, lat, lng, cover_image_url, is_featured, created_at, updated_at
`

type AdminUpdateCompoundParams struct {
	AreaID        pgtype.UUID    `json:"area_id"`
	Slug          string         `json:"slug"`
	NameAr        string         `json:"name_ar"`
	NameEn        string         `json:"name_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	Amenities     []string       `json:"amenities"`
	BeachType     BeachTypeEnum  `json:"beach_type"`
	GateInfoAr    *string        `json:"gate_info_ar"`
	GateInfoEn    *string        `json:"gate_info_en"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	CoverImageUrl *string        `json:"cover_image_url"`
	IsFeatured    bool           `json:"is_featured"`
	ID            pgtype.UUID    `json:"id"`
}

func (q *Queries) AdminUpdateCompound(ctx context.Context, arg AdminUpdateCompoundParams) (Compound, error) {
	row := q.db.QueryRow(ctx, adminUpdateCompound,
		arg.AreaID,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.Amenities,
		arg.BeachType,
		arg.GateInfoAr,
		arg.GateInfoEn,
		arg.Lat,
		arg.Lng,
		arg.CoverImageUrl,
		arg.IsFeatured,
		arg.ID,
	)
	var i Compound
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.Amenities,
		&i.BeachType,
		&i.GateInfoAr,
		&i.GateInfoEn,
		&i.Lat,
		&i.Lng,
		&i.CoverImageUrl,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
