// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminClearUnitCover = `-- name: AdminClearUnitCover :exec
UPDATE unit_images SET is_cover = false
WHERE unit_id = $1 AND is_cover AND id <> $2
`

type AdminClearUnitCoverParams struct {
	UnitID pgtype.UUID `json:"unit_id"`
	KeepID pgtype.UUID `json:"keep_id"`
}

func (q *Queries) AdminClearUnitCover(ctx context.Context, arg AdminClearUnitCoverParams) error {
	_, err := q.db.Exec(ctx, adminClearUnitCover, arg.UnitID, arg.KeepID)
	return err
}

const adminCreateUnitImage = `-- name: AdminCreateUnitImage :one
INSERT INTO unit_images (unit_id, url, sort, is_cover)
VALUES (
  $1, $2,
  (SELECT COALESCE(MAX(sort) + 1, 0) FROM unit_images WHERE unit_id = $1),
  NOT EXISTS (SELECT 1 FROM unit_images WHERE unit_id = $1 AND is_cover)
)
RETURNING id, unit_id, url, alt_ar, alt_en, sort, is_cover, created_at, updated_at
`

type AdminCreateUnitImageParams struct {
	UnitID pgtype.UUID `json:"unit_id"`
	Url    string      `json:"url"`
}

// Appends at the end of the sort order; the first image becomes the cover.
func (q *Queries) AdminCreateUnitImage(ctx context.Context, arg AdminCreateUnitImageParams) (UnitImage, error) {
	row := q.db.QueryRow(ctx, adminCreateUnitImage, arg.UnitID, arg.Url)
	var i UnitImage
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Url,
		&i.AltAr,
		&i.AltEn,
		&i.Sort,
		&i.IsCover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteUnitImage = `-- name: AdminDeleteUnitImage :one
DELETE FROM unit_images WHERE id = $1 AND unit_id = $2 RETURNING url
`

type AdminDeleteUnitImageParams struct {
	ID     pgtype.UUID `json:"id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

func (q *Queries) AdminDeleteUnitImage(ctx context.Context, arg AdminDeleteUnitImageParams) (string, error) {
	row := q.db.QueryRow(ctx, adminDeleteUnitImage, arg.ID, arg.UnitID)
	var url string
	err := row.Scan(&url)
	return url, err
}

const adminGetUnitImage = `-- name: AdminGetUnitImage :one
SELECT id, unit_id, url, alt_ar, alt_en, sort, is_cover, created_at, updated_at FROM unit_images WHERE id = $1 AND unit_id = $2
`

type AdminGetUnitImageParams struct {
	ID     pgtype.UUID `json:"id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

func (q *Queries) AdminGetUnitImage(ctx context.Context, arg AdminGetUnitImageParams) (UnitImage, error) {
	row := q.db.QueryRow(ctx, adminGetUnitImage, arg.ID, arg.UnitID)
	var i UnitImage
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Url,
		&i.AltAr,
		&i.AltEn,
		&i.Sort,
		&i.IsCover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminLockUnit = `-- name: AdminLockUnit :one
SELECT id FROM units WHERE id = $1 FOR UPDATE
`

// Serialises image writes per unit so sort/cover decisions can't race.
func (q *Queries) AdminLockUnit(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, adminLockUnit, id)
	err := row.Scan(&id)
	return id, err
}

const adminUpdateUnitImage = `-- name: AdminUpdateUnitImage :one
UPDATE unit_images
SET alt_ar = $1, alt_en = $2, sort = $3, is_cover = $4
WHERE id = $5
RETURNING id, unit_id, url, alt_ar, alt_en, sort, is_cover, created_at, updated_at
`

type AdminUpdateUnitImageParams struct {
	AltAr   *string     `json:"alt_ar"`
	AltEn   *string     `json:"alt_en"`
	Sort    int16       `json:"sort"`
	IsCover bool        `json:"is_cover"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateUnitImage(ctx context.Context, arg AdminUpdateUnitImageParams) (UnitImage, error) {
	row := q.db.QueryRow(ctx, adminUpdateUnitImage,
		arg.AltAr,
		arg.AltEn,
		arg.Sort,
		arg.IsCover,
		arg.ID,
	)
	var i UnitImage
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Url,
		&i.AltAr,
		&i.AltEn,
		&i.Sort,
		&i.IsCover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
