// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_owners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreateOwner = `-- name: AdminCreateOwner :one
INSERT INTO owners (name, phone, email, national_id, notes, commission_pct)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, phone, email, national_id, notes, commission_pct, created_at, updated_at
`

type AdminCreateOwnerParams struct {
	Name          string  `json:"name"`
	Phone         string  `json:"phone"`
	Email         *string `json:"email"`
	NationalID    *string `json:"national_id"`
	Notes         *string `json:"notes"`
	CommissionPct int16   `json:"commission_pct"`
}

func (q *Queries) AdminCreateOwner(ctx context.Context, arg AdminCreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, adminCreateOwner,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.NationalID,
		arg.Notes,
		arg.CommissionPct,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.NationalID,
		&i.Notes,
		&i.CommissionPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteOwner = `-- name: AdminDeleteOwner :execrows
DELETE FROM owners WHERE id = $1
`

func (q *Queries) AdminDeleteOwner(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteOwner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetOwner = `-- name: AdminGetOwner :one
SELECT id, name, phone, email, national_id, notes, commission_pct, created_at, updated_at FROM owners WHERE id = $1
`

func (q *Queries) AdminGetOwner(ctx context.Context, id pgtype.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, adminGetOwner, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.NationalID,
		&i.Notes,
		&i.CommissionPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListOwners = `-- name: AdminListOwners :many
SELECT id, name, phone, email, national_id, notes, commission_pct, created_at, updated_at FROM owners ORDER BY name ASC
`

func (q *Queries) AdminListOwners(ctx context.Context) ([]Owner, error) {
	rows, err := q.db.Query(ctx, adminListOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Owner{}
	for rows.Next() {
		var i Owner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.NationalID,
			&i.Notes,
			&i.CommissionPct,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateOwner = `-- name: AdminUpdateOwner :one
UPDATE owners
SET name = $1, phone = $2, email = $3, national_id = $4,
    notes = $5, commission_pct = $6
WHERE id = $7
RETURNING id, name, phone, email, national_id, notes, commission_pct, created_at, updated_at
`

type AdminUpdateOwnerParams struct {
	Name          string      `json:"name"`
	Phone         string      `json:"phone"`
	Email         *string     `json:"email"`
	NationalID    *string     `json:"national_id"`
	Notes         *string     `json:"notes"`
	CommissionPct int16       `json:"commission_pct"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateOwner(ctx context.Context, arg AdminUpdateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, adminUpdateOwner,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.NationalID,
		arg.Notes,
		arg.CommissionPct,
		arg.ID,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.NationalID,
		&i.Notes,
		&i.CommissionPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
