// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: areas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT id, slug, name_ar, name_en, region, km_marker, sort_order
FROM areas WHERE slug = $1
`

type GetAreaBySlugRow struct {
	ID        pgtype.UUID `json:"id"`
	Slug      string      `json:"slug"`
	NameAr    string      `json:"name_ar"`
	NameEn    string      `json:"name_en"`
	Region    RegionEnum  `json:"region"`
	KmMarker  *int32      `json:"km_marker"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (GetAreaBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i GetAreaBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Region,
		&i.KmMarker,
		&i.SortOrder,
	)
	return i, err
}

const listAreasWithUnitCount = `-- name: ListAreasWithUnitCount :many
SELECT
  a.id, a.slug, a.name_ar, a.name_en, a.region, a.km_marker, a.sort_order,
  COUNT(u.id) FILTER (WHERE u.status = 'active') AS unit_count
FROM areas a
LEFT JOIN compounds c ON c.area_id = a.id
LEFT JOIN units u     ON u.compound_id = c.id
GROUP BY a.id
ORDER BY a.sort_order ASC, a.name_en ASC
`

type ListAreasWithUnitCountRow struct {
	ID        pgtype.UUID `json:"id"`
	Slug      string      `json:"slug"`
	NameAr    string      `json:"name_ar"`
	NameEn    string      `json:"name_en"`
	Region    RegionEnum  `json:"region"`
	KmMarker  *int32      `json:"km_marker"`
	SortOrder int32       `json:"sort_order"`
	UnitCount int64       `json:"unit_count"`
}

func (q *Queries) ListAreasWithUnitCount(ctx context.Context) ([]ListAreasWithUnitCountRow, error) {
	rows, err := q.db.Query(ctx, listAreasWithUnitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAreasWithUnitCountRow{}
	for rows.Next() {
		var i ListAreasWithUnitCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.Region,
			&i.KmMarker,
			&i.SortOrder,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedCompoundsByAreaID = `-- name: ListFeaturedCompoundsByAreaID :many
SELECT id, area_id, slug, name_ar, name_en, description_ar, description_en,
       amenities, beach_type, gate_info_ar, gate_info_en, lat, lng,
       cover_image_url, is_featured
FROM compounds
WHERE area_id = $1 AND is_featured = true
ORDER BY name_en ASC
`

type ListFeaturedCompoundsByAreaIDRow struct {
	ID            pgtype.UUID    `json:"id"`
	AreaID        pgtype.UUID    `json:"area_id"`
	Slug          string         `json:"slug"`
	NameAr        string         `json:"name_ar"`
	NameEn        string         `json:"name_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	Amenities     []string       `json:"amenities"`
	BeachType     BeachTypeEnum  `json:"beach_type"`
	GateInfoAr    *string        `json:"gate_info_ar"`
	GateInfoEn    *string        `json:"gate_info_en"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	CoverImageUrl *string        `json:"cover_image_url"`
	IsFeatured    bool           `json:"is_featured"`
}

func (q *Queries) ListFeaturedCompoundsByAreaID(ctx context.Context, areaID pgtype.UUID) ([]ListFeaturedCompoundsByAreaIDRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedCompoundsByAreaID, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedCompoundsByAreaIDRow{}
	for rows.Next() {
		var i ListFeaturedCompoundsByAreaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.Amenities,
			&i.BeachType,
			&i.GateInfoAr,
			&i.GateInfoEn,
			&i.Lat,
			&i.Lng,
			&i.CoverImageUrl,
			&i.IsFeatured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
