// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booking.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListBookings = `-- name: AdminListBookings :many
SELECT b.id, b.ref, b.check_in, b.check_out, b.nights, b.guests, b.status, b.total, b.created_at,
       u.id AS unit_id, u.title_ar AS unit_title_ar, u.title_en AS unit_title_en,
       cu.name AS customer_name, cu.phone AS customer_phone
FROM bookings b
JOIN units u      ON u.id = b.unit_id
JOIN customers cu ON cu.id = b.customer_id
WHERE ($1::booking_status_enum IS NULL OR b.status = $1::booking_status_enum)
  AND ($2::uuid IS NULL OR b.unit_id = $2::uuid)
  AND ($3::text IS NULL OR b.ref ILIKE '%' || $3::text || '%'
       OR cu.phone LIKE '%' || $3::text || '%' OR cu.name ILIKE '%' || $3::text || '%')
ORDER BY b.check_in DESC, b.created_at DESC
LIMIT 500
`

type AdminListBookingsParams struct {
	Status NullBookingStatusEnum `json:"status"`
	UnitID pgtype.UUID           `json:"unit_id"`
	Q      *string               `json:"q"`
}

type AdminListBookingsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Ref           string             `json:"ref"`
	CheckIn       time.Time          `json:"check_in"`
	CheckOut      time.Time          `json:"check_out"`
	Nights        *int32             `json:"nights"`
	Guests        int16              `json:"guests"`
	Status        BookingStatusEnum  `json:"status"`
	Total         int64              `json:"total"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UnitID        pgtype.UUID        `json:"unit_id"`
	UnitTitleAr   string             `json:"unit_title_ar"`
	UnitTitleEn   string             `json:"unit_title_en"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
}

func (q *Queries) AdminListBookings(ctx context.Context, arg AdminListBookingsParams) ([]AdminListBookingsRow, error) {
	rows, err := q.db.Query(ctx, adminListBookings, arg.Status, arg.UnitID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListBookingsRow{}
	for rows.Next() {
		var i AdminListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.CheckIn,
			&i.CheckOut,
			&i.Nights,
			&i.Guests,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.UnitID,
			&i.UnitTitleAr,
			&i.UnitTitleEn,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'cancelled', cancelled_at = now(), cancel_reason = $1
WHERE id = $2 AND status IN ('pending_payment','awaiting_verification','confirmed')
RETURNING id
`

type CancelBookingParams struct {
	Reason *string     `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelBooking, arg.Reason, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countFailedLogins = `-- name: CountFailedLogins :one
SELECT
  COUNT(*) FILTER (WHERE phone = $1 AND created_at > now() - interval '15 minutes') AS by_phone,
  COUNT(*) FILTER (WHERE ip = $2 AND created_at > now() - interval '1 hour') AS by_ip
FROM auth_attempts
WHERE kind = 'login' AND NOT ok AND (phone = $1 OR ip = $2)
`

type CountFailedLoginsParams struct {
	Phone string `json:"phone"`
	Ip    string `json:"ip"`
}

type CountFailedLoginsRow struct {
	ByPhone int64 `json:"by_phone"`
	ByIp    int64 `json:"by_ip"`
}

func (q *Queries) CountFailedLogins(ctx context.Context, arg CountFailedLoginsParams) (CountFailedLoginsRow, error) {
	row := q.db.QueryRow(ctx, countFailedLogins, arg.Phone, arg.Ip)
	var i CountFailedLoginsRow
	err := row.Scan(&i.ByPhone, &i.ByIp)
	return i, err
}

const countOverlappingStays = `-- name: CountOverlappingStays :one
SELECT COUNT(*) FROM bookings b
WHERE b.unit_id = $1
  AND b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
  AND daterange(b.check_in, b.check_out + $2::int, '[)') && daterange($3::date, $4::date, '[)')
`

type CountOverlappingStaysParams struct {
	UnitID     pgtype.UUID `json:"unit_id"`
	BufferDays int32       `json:"buffer_days"`
	CheckIn    time.Time   `json:"check_in"`
	CheckOut   time.Time   `json:"check_out"`
}

// Occupying bookings that clash with [check_in, check_out), counting each
// booking's turnover days after its check-out as taken too.
func (q *Queries) CountOverlappingStays(ctx context.Context, arg CountOverlappingStaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOverlappingStays,
		arg.UnitID,
		arg.BufferDays,
		arg.CheckIn,
		arg.CheckOut,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegistrations = `-- name: CountRecentRegistrations :one
SELECT COUNT(*) FROM auth_attempts WHERE kind = 'register' AND ip = $1 AND created_at > now() - interval '1 hour'
`

func (q *Queries) CountRecentRegistrations(ctx context.Context, ip string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegistrations, ip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (ref, unit_id, customer_id, check_in, check_out, guests, status, nightly_price, total, deposit_due, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'web')
RETURNING id, ref
`

type CreateBookingParams struct {
	Ref          string            `json:"ref"`
	UnitID       pgtype.UUID       `json:"unit_id"`
	CustomerID   pgtype.UUID       `json:"customer_id"`
	CheckIn      time.Time         `json:"check_in"`
	CheckOut     time.Time         `json:"check_out"`
	Guests       int16             `json:"guests"`
	Status       BookingStatusEnum `json:"status"`
	NightlyPrice int64             `json:"nightly_price"`
	Total        int64             `json:"total"`
	DepositDue   int64             `json:"deposit_due"`
}

type CreateBookingRow struct {
	ID  pgtype.UUID `json:"id"`
	Ref string      `json:"ref"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Ref,
		arg.UnitID,
		arg.CustomerID,
		arg.CheckIn,
		arg.CheckOut,
		arg.Guests,
		arg.Status,
		arg.NightlyPrice,
		arg.Total,
		arg.DepositDue,
	)
	var i CreateBookingRow
	err := row.Scan(&i.ID, &i.Ref)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (phone, name, password_hash) VALUES ($1, $2, $3)
ON CONFLICT (phone) DO UPDATE SET name = EXCLUDED.name, password_hash = EXCLUDED.password_hash
WHERE customers.password_hash IS NULL
RETURNING id, phone, name, email, created_at, updated_at, password_hash
`

type CreateCustomerParams struct {
	Phone        string  `json:"phone"`
	Name         string  `json:"name"`
	PasswordHash *string `json:"password_hash"`
}

// A phone that exists without a password (from the old SMS sign-in) is
// claimed by the first registration; one with a password is taken.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Phone, arg.Name, arg.PasswordHash)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getBookingView = `-- name: GetBookingView :one
SELECT b.id, b.ref, b.check_in, b.check_out, b.nights, b.guests, b.status, b.nightly_price, b.total,
       b.deposit_due, b.source, b.cancelled_at, b.cancel_reason, b.created_at, b.customer_id,
       u.id AS unit_id, u.slug AS unit_slug, u.title_ar AS unit_title_ar, u.title_en AS unit_title_en,
       c.name_ar AS compound_name_ar, c.name_en AS compound_name_en,
       cu.name AS customer_name, cu.phone AS customer_phone,
       ci.url AS cover_url
FROM bookings b
JOIN units u      ON u.id = b.unit_id
JOIN compounds c  ON c.id = u.compound_id
JOIN customers cu ON cu.id = b.customer_id
LEFT JOIN unit_images ci ON ci.unit_id = u.id AND ci.is_cover
WHERE ($1::text IS NULL OR b.ref = $1::text)
  AND ($2::uuid IS NULL OR b.id = $2::uuid)
`

type GetBookingViewParams struct {
	Ref *string     `json:"ref"`
	ID  pgtype.UUID `json:"id"`
}

type GetBookingViewRow struct {
	ID             pgtype.UUID        `json:"id"`
	Ref            string             `json:"ref"`
	CheckIn        time.Time          `json:"check_in"`
	CheckOut       time.Time          `json:"check_out"`
	Nights         *int32             `json:"nights"`
	Guests         int16              `json:"guests"`
	Status         BookingStatusEnum  `json:"status"`
	NightlyPrice   int64              `json:"nightly_price"`
	Total          int64              `json:"total"`
	DepositDue     int64              `json:"deposit_due"`
	Source         string             `json:"source"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason   *string            `json:"cancel_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	UnitSlug       string             `json:"unit_slug"`
	UnitTitleAr    string             `json:"unit_title_ar"`
	UnitTitleEn    string             `json:"unit_title_en"`
	CompoundNameAr string             `json:"compound_name_ar"`
	CompoundNameEn string             `json:"compound_name_en"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	CoverUrl       *string            `json:"cover_url"`
}

// A booking with what its pages show about the unit and guest.
func (q *Queries) GetBookingView(ctx context.Context, arg GetBookingViewParams) (GetBookingViewRow, error) {
	row := q.db.QueryRow(ctx, getBookingView, arg.Ref, arg.ID)
	var i GetBookingViewRow
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.CheckIn,
		&i.CheckOut,
		&i.Nights,
		&i.Guests,
		&i.Status,
		&i.NightlyPrice,
		&i.Total,
		&i.DepositDue,
		&i.Source,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.CustomerID,
		&i.UnitID,
		&i.UnitSlug,
		&i.UnitTitleAr,
		&i.UnitTitleEn,
		&i.CompoundNameAr,
		&i.CompoundNameEn,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CoverUrl,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, phone, name, email, created_at, updated_at, password_hash FROM customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, phone, name, email, created_at, updated_at, password_hash FROM customers WHERE phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listCustomerBookings = `-- name: ListCustomerBookings :many
SELECT b.id, b.ref, b.check_in, b.check_out, b.nights, b.guests, b.status, b.total, b.created_at,
       u.slug AS unit_slug, u.title_ar AS unit_title_ar, u.title_en AS unit_title_en, ci.url AS cover_url
FROM bookings b
JOIN units u ON u.id = b.unit_id
LEFT JOIN unit_images ci ON ci.unit_id = u.id AND ci.is_cover
WHERE b.customer_id = $1
ORDER BY b.created_at DESC
`

type ListCustomerBookingsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Ref         string             `json:"ref"`
	CheckIn     time.Time          `json:"check_in"`
	CheckOut    time.Time          `json:"check_out"`
	Nights      *int32             `json:"nights"`
	Guests      int16              `json:"guests"`
	Status      BookingStatusEnum  `json:"status"`
	Total       int64              `json:"total"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnitSlug    string             `json:"unit_slug"`
	UnitTitleAr string             `json:"unit_title_ar"`
	UnitTitleEn string             `json:"unit_title_en"`
	CoverUrl    *string            `json:"cover_url"`
}

func (q *Queries) ListCustomerBookings(ctx context.Context, customerID pgtype.UUID) ([]ListCustomerBookingsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerBookings, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerBookingsRow{}
	for rows.Next() {
		var i ListCustomerBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.CheckIn,
			&i.CheckOut,
			&i.Nights,
			&i.Guests,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.UnitSlug,
			&i.UnitTitleAr,
			&i.UnitTitleEn,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccupiedStays = `-- name: ListOccupiedStays :many
SELECT b.check_in, (b.check_out + $1::int)::date AS blocked_until
FROM bookings b
WHERE b.unit_id = $2
  AND b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
  AND b.check_in <= $3::date AND (b.check_out + $1::int) > $4::date
`

type ListOccupiedStaysParams struct {
	BufferDays int32       `json:"buffer_days"`
	UnitID     pgtype.UUID `json:"unit_id"`
	ToDate     time.Time   `json:"to_date"`
	FromDate   time.Time   `json:"from_date"`
}

type ListOccupiedStaysRow struct {
	CheckIn      time.Time `json:"check_in"`
	BlockedUntil time.Time `json:"blocked_until"`
}

// Stays that touch a date range, with the unit's turnover days added.
func (q *Queries) ListOccupiedStays(ctx context.Context, arg ListOccupiedStaysParams) ([]ListOccupiedStaysRow, error) {
	rows, err := q.db.Query(ctx, listOccupiedStays,
		arg.BufferDays,
		arg.UnitID,
		arg.ToDate,
		arg.FromDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccupiedStaysRow{}
	for rows.Next() {
		var i ListOccupiedStaysRow
		if err := rows.Scan(&i.CheckIn, &i.BlockedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthAttempt = `-- name: RecordAuthAttempt :exec
INSERT INTO auth_attempts (kind, phone, ip, ok) VALUES ($1, $2, $3, $4)
`

type RecordAuthAttemptParams struct {
	Kind  string `json:"kind"`
	Phone string `json:"phone"`
	Ip    string `json:"ip"`
	Ok    bool   `json:"ok"`
}

func (q *Queries) RecordAuthAttempt(ctx context.Context, arg RecordAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAuthAttempt,
		arg.Kind,
		arg.Phone,
		arg.Ip,
		arg.Ok,
	)
	return err
}

const setCustomerName = `-- name: SetCustomerName :one
UPDATE customers SET name = $1 WHERE id = $2 RETURNING id, phone, name, email, created_at, updated_at, password_hash
`

type SetCustomerNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) SetCustomerName(ctx context.Context, arg SetCustomerNameParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerName, arg.Name, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const setCustomerPassword = `-- name: SetCustomerPassword :execrows
UPDATE customers SET password_hash = $1 WHERE id = $2
`

type SetCustomerPasswordParams struct {
	PasswordHash *string     `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetCustomerPassword(ctx context.Context, arg SetCustomerPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
