// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calendar.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteManualDays = `-- name: DeleteManualDays :exec
DELETE FROM unit_calendar
WHERE unit_id = $1 AND source = 'manual' AND date BETWEEN $2 AND $3
`

type DeleteManualDaysParams struct {
	UnitID   pgtype.UUID `json:"unit_id"`
	FromDate time.Time   `json:"from_date"`
	ToDate   time.Time   `json:"to_date"`
}

func (q *Queries) DeleteManualDays(ctx context.Context, arg DeleteManualDaysParams) error {
	_, err := q.db.Exec(ctx, deleteManualDays, arg.UnitID, arg.FromDate, arg.ToDate)
	return err
}

const deleteRuleDays = `-- name: DeleteRuleDays :exec
DELETE FROM unit_calendar
WHERE unit_id = $1 AND source = 'rule' AND date BETWEEN $2 AND $3
`

type DeleteRuleDaysParams struct {
	UnitID   pgtype.UUID `json:"unit_id"`
	FromDate time.Time   `json:"from_date"`
	ToDate   time.Time   `json:"to_date"`
}

func (q *Queries) DeleteRuleDays(ctx context.Context, arg DeleteRuleDaysParams) error {
	_, err := q.db.Exec(ctx, deleteRuleDays, arg.UnitID, arg.FromDate, arg.ToDate)
	return err
}

const getPricingUnitBySlug = `-- name: GetPricingUnitBySlug :one
SELECT id, slug, base_guests, max_guests, cleaning_fee, deposit_pct, security_deposit,
       extra_guest_fee, advance_notice_hours, max_advance_days
FROM units WHERE slug = $1 AND status = 'active'
`

type GetPricingUnitBySlugRow struct {
	ID                 pgtype.UUID `json:"id"`
	Slug               string      `json:"slug"`
	BaseGuests         int16       `json:"base_guests"`
	MaxGuests          int16       `json:"max_guests"`
	CleaningFee        int64       `json:"cleaning_fee"`
	DepositPct         int16       `json:"deposit_pct"`
	SecurityDeposit    int64       `json:"security_deposit"`
	ExtraGuestFee      int64       `json:"extra_guest_fee"`
	AdvanceNoticeHours int32       `json:"advance_notice_hours"`
	MaxAdvanceDays     int32       `json:"max_advance_days"`
}

// What the quote needs; archived and non-active units are not bookable.
func (q *Queries) GetPricingUnitBySlug(ctx context.Context, slug string) (GetPricingUnitBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPricingUnitBySlug, slug)
	var i GetPricingUnitBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.BaseGuests,
		&i.MaxGuests,
		&i.CleaningFee,
		&i.DepositPct,
		&i.SecurityDeposit,
		&i.ExtraGuestFee,
		&i.AdvanceNoticeHours,
		&i.MaxAdvanceDays,
	)
	return i, err
}

const insertRuleDays = `-- name: InsertRuleDays :exec
INSERT INTO unit_calendar (unit_id, date, price, min_nights, allowed_checkin, is_available, source, season_id)
SELECT $1, unnest($2::date[]), unnest($3::bigint[]), unnest($4::smallint[]),
       unnest($5::boolean[]), true, 'rule', unnest($6::uuid[])
ON CONFLICT (unit_id, date) DO NOTHING
`

type InsertRuleDaysParams struct {
	UnitID         pgtype.UUID   `json:"unit_id"`
	Dates          []time.Time   `json:"dates"`
	Prices         []int64       `json:"prices"`
	MinNights      []int16       `json:"min_nights"`
	AllowedCheckin []bool        `json:"allowed_checkin"`
	SeasonIds      []pgtype.UUID `json:"season_ids"`
}

// Manual rows already on a date win: they are never overwritten here.
func (q *Queries) InsertRuleDays(ctx context.Context, arg InsertRuleDaysParams) error {
	_, err := q.db.Exec(ctx, insertRuleDays,
		arg.UnitID,
		arg.Dates,
		arg.Prices,
		arg.MinNights,
		arg.AllowedCheckin,
		arg.SeasonIds,
	)
	return err
}

const listCalendar = `-- name: ListCalendar :many
SELECT uc.date, uc.price, uc.min_nights, uc.allowed_checkin, uc.is_available, uc.source, uc.note,
       s.name_ar AS season_name_ar, s.name_en AS season_name_en
FROM unit_calendar uc
LEFT JOIN seasons s ON s.id = uc.season_id
WHERE uc.unit_id = $1 AND uc.date BETWEEN $2 AND $3
ORDER BY uc.date
`

type ListCalendarParams struct {
	UnitID   pgtype.UUID `json:"unit_id"`
	FromDate time.Time   `json:"from_date"`
	ToDate   time.Time   `json:"to_date"`
}

type ListCalendarRow struct {
	Date           time.Time          `json:"date"`
	Price          int64              `json:"price"`
	MinNights      int16              `json:"min_nights"`
	AllowedCheckin bool               `json:"allowed_checkin"`
	IsAvailable    bool               `json:"is_available"`
	Source         CalendarSourceEnum `json:"source"`
	Note           *string            `json:"note"`
	SeasonNameAr   *string            `json:"season_name_ar"`
	SeasonNameEn   *string            `json:"season_name_en"`
}

func (q *Queries) ListCalendar(ctx context.Context, arg ListCalendarParams) ([]ListCalendarRow, error) {
	rows, err := q.db.Query(ctx, listCalendar, arg.UnitID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarRow{}
	for rows.Next() {
		var i ListCalendarRow
		if err := rows.Scan(
			&i.Date,
			&i.Price,
			&i.MinNights,
			&i.AllowedCheckin,
			&i.IsAvailable,
			&i.Source,
			&i.Note,
			&i.SeasonNameAr,
			&i.SeasonNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overrideDays = `-- name: OverrideDays :execrows
INSERT INTO unit_calendar (unit_id, date, price, min_nights, allowed_checkin, is_available, source, season_id, note)
SELECT $1, g.d::date,
       COALESCE($2::bigint, uc.price),
       COALESCE($3::smallint, uc.min_nights, u.min_nights_default),
       COALESCE(uc.allowed_checkin, true),
       COALESCE($4::boolean, uc.is_available, true),
       'manual', uc.season_id,
       COALESCE($5::text, uc.note)
FROM generate_series($6::date, $7::date, interval '1 day') AS g(d)
JOIN units u ON u.id = $1
LEFT JOIN unit_calendar uc ON uc.unit_id = $1 AND uc.date = g.d::date
WHERE COALESCE($2::bigint, uc.price) IS NOT NULL
ON CONFLICT (unit_id, date) DO UPDATE
SET price = EXCLUDED.price, min_nights = EXCLUDED.min_nights, is_available = EXCLUDED.is_available,
    note = EXCLUDED.note, source = 'manual'
`

type OverrideDaysParams struct {
	UnitID      pgtype.UUID `json:"unit_id"`
	Price       *int64      `json:"price"`
	MinNights   *int16      `json:"min_nights"`
	IsAvailable *bool       `json:"is_available"`
	Note        *string     `json:"note"`
	FromDate    time.Time   `json:"from_date"`
	ToDate      time.Time   `json:"to_date"`
}

// Sets the given fields on every date in the range and marks them manual.
// A date with no row yet needs a price, so it is skipped unless one is given.
func (q *Queries) OverrideDays(ctx context.Context, arg OverrideDaysParams) (int64, error) {
	result, err := q.db.Exec(ctx, overrideDays,
		arg.UnitID,
		arg.Price,
		arg.MinNights,
		arg.IsAvailable,
		arg.Note,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
