// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: compounds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUnitsByCompoundID = `-- name: CountActiveUnitsByCompoundID :one
SELECT COUNT(*) FROM units WHERE compound_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveUnitsByCompoundID(ctx context.Context, compoundID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUnitsByCompoundID, compoundID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompounds = `-- name: CountCompounds :one
SELECT COUNT(*)
FROM compounds c
JOIN areas a ON a.id = c.area_id
WHERE ($1::text IS NULL OR a.slug = $1::text)
`

func (q *Queries) CountCompounds(ctx context.Context, areaSlug *string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompounds, areaSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompoundBySlug = `-- name: GetCompoundBySlug :one
SELECT
  c.id, c.area_id, c.slug, c.name_ar, c.name_en, c.description_ar, c.description_en,
  c.amenities, c.beach_type, c.gate_info_ar, c.gate_info_en, c.lat, c.lng,
  c.cover_image_url, c.is_featured,
  a.slug AS area_slug, a.name_ar AS area_name_ar, a.name_en AS area_name_en
FROM compounds c
JOIN areas a ON a.id = c.area_id
WHERE c.slug = $1
`

type GetCompoundBySlugRow struct {
	ID            pgtype.UUID    `json:"id"`
	AreaID        pgtype.UUID    `json:"area_id"`
	Slug          string         `json:"slug"`
	NameAr        string         `json:"name_ar"`
	NameEn        string         `json:"name_en"`
	DescriptionAr string         `json:"description_ar"`
	DescriptionEn string         `json:"description_en"`
	Amenities     []string       `json:"amenities"`
	BeachType     BeachTypeEnum  `json:"beach_type"`
	GateInfoAr    *string        `json:"gate_info_ar"`
	GateInfoEn    *string        `json:"gate_info_en"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	CoverImageUrl *string        `json:"cover_image_url"`
	IsFeatured    bool           `json:"is_featured"`
	AreaSlug      string         `json:"area_slug"`
	AreaNameAr    string         `json:"area_name_ar"`
	AreaNameEn    string         `json:"area_name_en"`
}

func (q *Queries) GetCompoundBySlug(ctx context.Context, slug string) (GetCompoundBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCompoundBySlug, slug)
	var i GetCompoundBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.Amenities,
		&i.BeachType,
		&i.GateInfoAr,
		&i.GateInfoEn,
		&i.Lat,
		&i.Lng,
		&i.CoverImageUrl,
		&i.IsFeatured,
		&i.AreaSlug,
		&i.AreaNameAr,
		&i.AreaNameEn,
	)
	return i, err
}

const listActiveUnitsByCompoundID = `-- name: ListActiveUnitsByCompoundID :many
SELECT id, compound_id, slug, title_ar, title_en, type, bedrooms, bathrooms,
       max_guests, sea_distance_m, view, status, created_at
FROM units
WHERE compound_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveUnitsByCompoundIDParams struct {
	CompoundID pgtype.UUID `json:"compound_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListActiveUnitsByCompoundIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	CompoundID   pgtype.UUID        `json:"compound_id"`
	Slug         string             `json:"slug"`
	TitleAr      string             `json:"title_ar"`
	TitleEn      string             `json:"title_en"`
	Type         UnitTypeEnum       `json:"type"`
	Bedrooms     int16              `json:"bedrooms"`
	Bathrooms    int16              `json:"bathrooms"`
	MaxGuests    int16              `json:"max_guests"`
	SeaDistanceM int32              `json:"sea_distance_m"`
	View         UnitViewEnum       `json:"view"`
	Status       UnitStatusEnum     `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveUnitsByCompoundID(ctx context.Context, arg ListActiveUnitsByCompoundIDParams) ([]ListActiveUnitsByCompoundIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveUnitsByCompoundID, arg.CompoundID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUnitsByCompoundIDRow{}
	for rows.Next() {
		var i ListActiveUnitsByCompoundIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CompoundID,
			&i.Slug,
			&i.TitleAr,
			&i.TitleEn,
			&i.Type,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.MaxGuests,
			&i.SeaDistanceM,
			&i.View,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompounds = `-- name: ListCompounds :many
SELECT
  c.id, c.area_id, c.slug, c.name_ar, c.name_en, c.description_ar, c.description_en,
  c.amenities, c.beach_type, c.cover_image_url, c.is_featured,
  a.slug AS area_slug
FROM compounds c
JOIN areas a ON a.id = c.area_id
WHERE ($1::text IS NULL OR a.slug = $1::text)
ORDER BY c.name_en ASC
LIMIT $3 OFFSET $2
`

type ListCompoundsParams struct {
	AreaSlug   *string `json:"area_slug"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

type ListCompoundsRow struct {
	ID            pgtype.UUID   `json:"id"`
	AreaID        pgtype.UUID   `json:"area_id"`
	Slug          string        `json:"slug"`
	NameAr        string        `json:"name_ar"`
	NameEn        string        `json:"name_en"`
	DescriptionAr string        `json:"description_ar"`
	DescriptionEn string        `json:"description_en"`
	Amenities     []string      `json:"amenities"`
	BeachType     BeachTypeEnum `json:"beach_type"`
	CoverImageUrl *string       `json:"cover_image_url"`
	IsFeatured    bool          `json:"is_featured"`
	AreaSlug      string        `json:"area_slug"`
}

func (q *Queries) ListCompounds(ctx context.Context, arg ListCompoundsParams) ([]ListCompoundsRow, error) {
	rows, err := q.db.Query(ctx, listCompounds, arg.AreaSlug, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompoundsRow{}
	for rows.Next() {
		var i ListCompoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.Amenities,
			&i.BeachType,
			&i.CoverImageUrl,
			&i.IsFeatured,
			&i.AreaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
