// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetCustomer = `-- name: AdminGetCustomer :one
SELECT id, name, phone, email, created_at, (password_hash IS NOT NULL)::boolean AS has_password
FROM customers WHERE id = $1
`

type AdminGetCustomerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Phone       string             `json:"phone"`
	Email       *string            `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	HasPassword bool               `json:"has_password"`
}

func (q *Queries) AdminGetCustomer(ctx context.Context, id pgtype.UUID) (AdminGetCustomerRow, error) {
	row := q.db.QueryRow(ctx, adminGetCustomer, id)
	var i AdminGetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.HasPassword,
	)
	return i, err
}

const adminListCustomers = `-- name: AdminListCustomers :many
SELECT cu.id, cu.name, cu.phone, cu.created_at,
       COUNT(b.id)::int AS bookings,
       COUNT(b.id) FILTER (WHERE b.status IN ('confirmed','checked_in','completed'))::int AS stays,
       COALESCE(SUM(b.paid_total), 0)::bigint AS paid_total,
       MAX(b.created_at)::timestamptz AS last_booked_at
FROM customers cu
LEFT JOIN bookings b ON b.customer_id = cu.id
WHERE $1::text IS NULL
   OR cu.name ILIKE '%' || $1::text || '%'
   OR cu.phone LIKE '%' || $1::text || '%'
GROUP BY cu.id
ORDER BY cu.created_at DESC
LIMIT 500
`

type AdminListCustomersRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Bookings     int32              `json:"bookings"`
	Stays        int32              `json:"stays"`
	PaidTotal    int64              `json:"paid_total"`
	LastBookedAt pgtype.Timestamptz `json:"last_booked_at"`
}

// Every guest account with a summary of their bookings; newest account first.
func (q *Queries) AdminListCustomers(ctx context.Context, search *string) ([]AdminListCustomersRow, error) {
	rows, err := q.db.Query(ctx, adminListCustomers, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCustomersRow{}
	for rows.Next() {
		var i AdminListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.CreatedAt,
			&i.Bookings,
			&i.Stays,
			&i.PaidTotal,
			&i.LastBookedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
