// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBookingsInRange = `-- name: CountBookingsInRange :one
SELECT COUNT(*) FROM bookings
WHERE unit_id = $1
  AND status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
  AND stay && daterange($2::date, $3::date, '[)')
`

type CountBookingsInRangeParams struct {
	UnitID    pgtype.UUID `json:"unit_id"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
}

// Occupying bookings on these nights of the unit, without turnover days.
func (q *Queries) CountBookingsInRange(ctx context.Context, arg CountBookingsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsInRange, arg.UnitID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :one
INSERT INTO unit_blocks (unit_id, start_date, end_date, note)
VALUES ($1, $2, $3, $4)
RETURNING id, unit_id, start_date, end_date, note, created_at
`

type CreateBlockParams struct {
	UnitID    pgtype.UUID `json:"unit_id"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	Note      string      `json:"note"`
}

type CreateBlockRow struct {
	ID        pgtype.UUID        `json:"id"`
	UnitID    pgtype.UUID        `json:"unit_id"`
	StartDate time.Time          `json:"start_date"`
	EndDate   time.Time          `json:"end_date"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.UnitID,
		arg.StartDate,
		arg.EndDate,
		arg.Note,
	)
	var i CreateBlockRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.StartDate,
		&i.EndDate,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM unit_blocks WHERE id = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlock, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockUnit = `-- name: LockUnit :one
SELECT id FROM units WHERE id = $1 FOR UPDATE
`

// Serialises bookings and blocks on one unit: both take this lock first.
func (q *Queries) LockUnit(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUnit, id)
	err := row.Scan(&id)
	return id, err
}

const timelineBlocks = `-- name: TimelineBlocks :many
SELECT id, unit_id, start_date, end_date, note
FROM unit_blocks
WHERE span && daterange($1::date, $2::date, '[)')
ORDER BY start_date
`

type TimelineBlocksParams struct {
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type TimelineBlocksRow struct {
	ID        pgtype.UUID `json:"id"`
	UnitID    pgtype.UUID `json:"unit_id"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	Note      string      `json:"note"`
}

func (q *Queries) TimelineBlocks(ctx context.Context, arg TimelineBlocksParams) ([]TimelineBlocksRow, error) {
	rows, err := q.db.Query(ctx, timelineBlocks, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineBlocksRow{}
	for rows.Next() {
		var i TimelineBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.StartDate,
			&i.EndDate,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timelineBookings = `-- name: TimelineBookings :many
SELECT b.id, b.ref, b.unit_id, b.status, b.check_in, b.check_out, cu.name AS customer_name
FROM bookings b
JOIN customers cu ON cu.id = b.customer_id
WHERE b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
  AND b.stay && daterange($1::date, $2::date, '[)')
ORDER BY b.check_in
`

type TimelineBookingsParams struct {
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type TimelineBookingsRow struct {
	ID           pgtype.UUID       `json:"id"`
	Ref          string            `json:"ref"`
	UnitID       pgtype.UUID       `json:"unit_id"`
	Status       BookingStatusEnum `json:"status"`
	CheckIn      time.Time         `json:"check_in"`
	CheckOut     time.Time         `json:"check_out"`
	CustomerName string            `json:"customer_name"`
}

func (q *Queries) TimelineBookings(ctx context.Context, arg TimelineBookingsParams) ([]TimelineBookingsRow, error) {
	rows, err := q.db.Query(ctx, timelineBookings, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineBookingsRow{}
	for rows.Next() {
		var i TimelineBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.UnitID,
			&i.Status,
			&i.CheckIn,
			&i.CheckOut,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timelineUnits = `-- name: TimelineUnits :many
SELECT u.id, u.slug, u.title_ar, u.title_en, u.status,
       c.name_ar AS compound_name_ar, c.name_en AS compound_name_en
FROM units u
JOIN compounds c ON c.id = u.compound_id
WHERE u.status <> 'archived'
ORDER BY c.name_en, u.title_en, u.id
`

type TimelineUnitsRow struct {
	ID             pgtype.UUID    `json:"id"`
	Slug           string         `json:"slug"`
	TitleAr        string         `json:"title_ar"`
	TitleEn        string         `json:"title_en"`
	Status         UnitStatusEnum `json:"status"`
	CompoundNameAr string         `json:"compound_name_ar"`
	CompoundNameEn string         `json:"compound_name_en"`
}

func (q *Queries) TimelineUnits(ctx context.Context) ([]TimelineUnitsRow, error) {
	rows, err := q.db.Query(ctx, timelineUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineUnitsRow{}
	for rows.Next() {
		var i TimelineUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleAr,
			&i.TitleEn,
			&i.Status,
			&i.CompoundNameAr,
			&i.CompoundNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayCounts = `-- name: TodayCounts :one
WITH w AS (
  SELECT $1::date AS day, daterange($1::date, $1::date + 7, '[)') AS week
)
SELECT
  (SELECT COUNT(*) FROM bookings b, w
   WHERE b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
     AND b.check_in <= w.day AND b.check_out > w.day) AS staying_tonight,
  (SELECT COUNT(*) FROM bookings
   WHERE status = 'pending_payment' AND hold_expires_at <= now() + interval '1 hour') AS holds_expiring,
  (SELECT COUNT(*) FROM units WHERE status = 'active') AS active_units,
  (SELECT COALESCE(SUM(upper(n.r) - lower(n.r)), 0)::bigint FROM (
     SELECT b.stay * w.week AS r
     FROM bookings b JOIN units u ON u.id = b.unit_id AND u.status = 'active', w
     WHERE b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
       AND b.stay && w.week
     UNION ALL
     SELECT k.span * w.week
     FROM unit_blocks k JOIN units u ON u.id = k.unit_id AND u.status = 'active', w
     WHERE k.span && w.week
   ) n) AS occupied_nights
`

type TodayCountsRow struct {
	StayingTonight int64 `json:"staying_tonight"`
	HoldsExpiring  int64 `json:"holds_expiring"`
	ActiveUnits    int64 `json:"active_units"`
	OccupiedNights int64 `json:"occupied_nights"`
}

// Stays tonight, holds running out within the hour, and the next seven
// nights of occupancy on active units (booked plus blocked nights).
func (q *Queries) TodayCounts(ctx context.Context, day time.Time) (TodayCountsRow, error) {
	row := q.db.QueryRow(ctx, todayCounts, day)
	var i TodayCountsRow
	err := row.Scan(
		&i.StayingTonight,
		&i.HoldsExpiring,
		&i.ActiveUnits,
		&i.OccupiedNights,
	)
	return i, err
}

const todayMovements = `-- name: TodayMovements :many
SELECT b.id, b.ref, b.status, b.check_in, b.check_out, b.nights, b.guests,
       cu.name AS customer_name, cu.phone AS customer_phone,
       u.id AS unit_id, u.title_ar AS unit_title_ar, u.title_en AS unit_title_en
FROM bookings b
JOIN customers cu ON cu.id = b.customer_id
JOIN units u      ON u.id = b.unit_id
WHERE b.status IN ('pending_payment','awaiting_verification','confirmed','checked_in','completed')
  AND (b.check_in = $1::date OR b.check_out = $1::date)
ORDER BY u.title_en, b.check_in
`

type TodayMovementsRow struct {
	ID            pgtype.UUID       `json:"id"`
	Ref           string            `json:"ref"`
	Status        BookingStatusEnum `json:"status"`
	CheckIn       time.Time         `json:"check_in"`
	CheckOut      time.Time         `json:"check_out"`
	Nights        *int32            `json:"nights"`
	Guests        int16             `json:"guests"`
	CustomerName  string            `json:"customer_name"`
	CustomerPhone string            `json:"customer_phone"`
	UnitID        pgtype.UUID       `json:"unit_id"`
	UnitTitleAr   string            `json:"unit_title_ar"`
	UnitTitleEn   string            `json:"unit_title_en"`
}

// Occupying bookings that check in or check out on @day.
func (q *Queries) TodayMovements(ctx context.Context, day time.Time) ([]TodayMovementsRow, error) {
	rows, err := q.db.Query(ctx, todayMovements, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodayMovementsRow{}
	for rows.Next() {
		var i TodayMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Status,
			&i.CheckIn,
			&i.CheckOut,
			&i.Nights,
			&i.Guests,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.UnitID,
			&i.UnitTitleAr,
			&i.UnitTitleEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
