// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BeachTypeEnum string

const (
	BeachTypeEnumSea    BeachTypeEnum = "sea"
	BeachTypeEnumLagoon BeachTypeEnum = "lagoon"
	BeachTypeEnumBoth   BeachTypeEnum = "both"
	BeachTypeEnumNone   BeachTypeEnum = "none"
)

func (e *BeachTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BeachTypeEnum(s)
	case string:
		*e = BeachTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BeachTypeEnum: %T", src)
	}
	return nil
}

type NullBeachTypeEnum struct {
	BeachTypeEnum BeachTypeEnum `json:"beach_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if BeachTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBeachTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BeachTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BeachTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBeachTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BeachTypeEnum), nil
}

type BookingStatusEnum string

const (
	BookingStatusEnumDraft                BookingStatusEnum = "draft"
	BookingStatusEnumPendingPayment       BookingStatusEnum = "pending_payment"
	BookingStatusEnumAwaitingVerification BookingStatusEnum = "awaiting_verification"
	BookingStatusEnumConfirmed            BookingStatusEnum = "confirmed"
	BookingStatusEnumCheckedIn            BookingStatusEnum = "checked_in"
	BookingStatusEnumCompleted            BookingStatusEnum = "completed"
	BookingStatusEnumExpired              BookingStatusEnum = "expired"
	BookingStatusEnumCancelled            BookingStatusEnum = "cancelled"
	BookingStatusEnumRefundPending        BookingStatusEnum = "refund_pending"
	BookingStatusEnumRefunded             BookingStatusEnum = "refunded"
)

func (e *BookingStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatusEnum(s)
	case string:
		*e = BookingStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatusEnum: %T", src)
	}
	return nil
}

type NullBookingStatusEnum struct {
	BookingStatusEnum BookingStatusEnum `json:"booking_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if BookingStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatusEnum), nil
}

type PaymentStatusEnum string

const (
	PaymentStatusEnumPending  PaymentStatusEnum = "pending"
	PaymentStatusEnumVerified PaymentStatusEnum = "verified"
	PaymentStatusEnumRejected PaymentStatusEnum = "rejected"
)

func (e *PaymentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatusEnum(s)
	case string:
		*e = PaymentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatusEnum: %T", src)
	}
	return nil
}

type NullPaymentStatusEnum struct {
	PaymentStatusEnum PaymentStatusEnum `json:"payment_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatusEnum), nil
}

type RegionEnum string

const (
	RegionEnumNorthCoast RegionEnum = "north_coast"
	RegionEnumSokhna     RegionEnum = "sokhna"
	RegionEnumGouna      RegionEnum = "gouna"
	RegionEnumRasSudr    RegionEnum = "ras_sudr"
	RegionEnumNewCairo   RegionEnum = "new_cairo"
)

func (e *RegionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegionEnum(s)
	case string:
		*e = RegionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RegionEnum: %T", src)
	}
	return nil
}

type NullRegionEnum struct {
	RegionEnum RegionEnum `json:"region_enum"`
	Valid      bool       `json:"valid"` // Valid is true if RegionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RegionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegionEnum), nil
}

type UnitStatusEnum string

const (
	UnitStatusEnumDraft    UnitStatusEnum = "draft"
	UnitStatusEnumActive   UnitStatusEnum = "active"
	UnitStatusEnumPaused   UnitStatusEnum = "paused"
	UnitStatusEnumArchived UnitStatusEnum = "archived"
)

func (e *UnitStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitStatusEnum(s)
	case string:
		*e = UnitStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitStatusEnum: %T", src)
	}
	return nil
}

type NullUnitStatusEnum struct {
	UnitStatusEnum UnitStatusEnum `json:"unit_status_enum"`
	Valid          bool           `json:"valid"` // Valid is true if UnitStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UnitStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitStatusEnum), nil
}

type UnitTypeEnum string

const (
	UnitTypeEnumChalet    UnitTypeEnum = "chalet"
	UnitTypeEnumVilla     UnitTypeEnum = "villa"
	UnitTypeEnumTwin      UnitTypeEnum = "twin"
	UnitTypeEnumTown      UnitTypeEnum = "town"
	UnitTypeEnumPenthouse UnitTypeEnum = "penthouse"
	UnitTypeEnumStudio    UnitTypeEnum = "studio"
	UnitTypeEnumApartment UnitTypeEnum = "apartment"
)

func (e *UnitTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitTypeEnum(s)
	case string:
		*e = UnitTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitTypeEnum: %T", src)
	}
	return nil
}

type NullUnitTypeEnum struct {
	UnitTypeEnum UnitTypeEnum `json:"unit_type_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UnitTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UnitTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitTypeEnum), nil
}

type UnitViewEnum string

const (
	UnitViewEnumSea    UnitViewEnum = "sea"
	UnitViewEnumLagoon UnitViewEnum = "lagoon"
	UnitViewEnumPool   UnitViewEnum = "pool"
	UnitViewEnumGarden UnitViewEnum = "garden"
	UnitViewEnumStreet UnitViewEnum = "street"
)

func (e *UnitViewEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitViewEnum(s)
	case string:
		*e = UnitViewEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitViewEnum: %T", src)
	}
	return nil
}

type NullUnitViewEnum struct {
	UnitViewEnum UnitViewEnum `json:"unit_view_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UnitViewEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitViewEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UnitViewEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitViewEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitViewEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitViewEnum), nil
}

type Area struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	NameAr    string             `json:"name_ar"`
	NameEn    string             `json:"name_en"`
	Region    RegionEnum         `json:"region"`
	KmMarker  *int32             `json:"km_marker"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthAttempt struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	Phone     string             `json:"phone"`
	Ip        string             `json:"ip"`
	Ok        bool               `json:"ok"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID                    pgtype.UUID               `json:"id"`
	Ref                   string                    `json:"ref"`
	UnitID                pgtype.UUID               `json:"unit_id"`
	CustomerID            pgtype.UUID               `json:"customer_id"`
	CheckIn               time.Time                 `json:"check_in"`
	CheckOut              time.Time                 `json:"check_out"`
	Nights                *int32                    `json:"nights"`
	Guests                int16                     `json:"guests"`
	Status                BookingStatusEnum         `json:"status"`
	NightlyPrice          int64                     `json:"nightly_price"`
	Total                 int64                     `json:"total"`
	DepositDue            int64                     `json:"deposit_due"`
	Source                string                    `json:"source"`
	CancelledAt           pgtype.Timestamptz        `json:"cancelled_at"`
	CancelReason          *string                   `json:"cancel_reason"`
	CreatedAt             pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz        `json:"updated_at"`
	Stay                  pgtype.Range[pgtype.Date] `json:"stay"`
	HoldExpiresAt         pgtype.Timestamptz        `json:"hold_expires_at"`
	PaidTotal             int64                     `json:"paid_total"`
	PaymentRejectionCount int16                     `json:"payment_rejection_count"`
}

type Compound struct {
	ID            pgtype.UUID        `json:"id"`
	AreaID        pgtype.UUID        `json:"area_id"`
	Slug          string             `json:"slug"`
	NameAr        string             `json:"name_ar"`
	NameEn        string             `json:"name_en"`
	DescriptionAr string             `json:"description_ar"`
	DescriptionEn string             `json:"description_en"`
	Amenities     []string           `json:"amenities"`
	BeachType     BeachTypeEnum      `json:"beach_type"`
	GateInfoAr    *string            `json:"gate_info_ar"`
	GateInfoEn    *string            `json:"gate_info_en"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lng           pgtype.Numeric     `json:"lng"`
	CoverImageUrl *string            `json:"cover_image_url"`
	IsFeatured    bool               `json:"is_featured"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID           pgtype.UUID        `json:"id"`
	Phone        string             `json:"phone"`
	Name         string             `json:"name"`
	Email        *string            `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash *string            `json:"password_hash"`
}

type InstapayAccount struct {
	ID         int16              `json:"id"`
	Address    string             `json:"address"`
	Mobile     string             `json:"mobile"`
	HolderName string             `json:"holder_name"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Owner struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Phone         string             `json:"phone"`
	Email         *string            `json:"email"`
	NationalID    *string            `json:"national_id"`
	Notes         *string            `json:"notes"`
	CommissionPct int16              `json:"commission_pct"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID              pgtype.UUID        `json:"id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	Method          string             `json:"method"`
	Status          PaymentStatusEnum  `json:"status"`
	Amount          int64              `json:"amount"`
	SenderName      string             `json:"sender_name"`
	SenderNumber    string             `json:"sender_number"`
	ProofKey        *string            `json:"proof_key"`
	ProofType       *string            `json:"proof_type"`
	RejectionReason *string            `json:"rejection_reason"`
	Notes           *string            `json:"notes"`
	RecordedBy      string             `json:"recorded_by"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Unit struct {
	ID                 pgtype.UUID        `json:"id"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	CompoundID         pgtype.UUID        `json:"compound_id"`
	Slug               string             `json:"slug"`
	TitleAr            string             `json:"title_ar"`
	TitleEn            string             `json:"title_en"`
	DescriptionAr      string             `json:"description_ar"`
	DescriptionEn      string             `json:"description_en"`
	HouseRulesAr       *string            `json:"house_rules_ar"`
	HouseRulesEn       *string            `json:"house_rules_en"`
	Type               UnitTypeEnum       `json:"type"`
	Bedrooms           int16              `json:"bedrooms"`
	Bathrooms          int16              `json:"bathrooms"`
	BaseGuests         int16              `json:"base_guests"`
	MaxGuests          int16              `json:"max_guests"`
	AreaSqm            *int32             `json:"area_sqm"`
	Floor              *int16             `json:"floor"`
	SeaDistanceM       int32              `json:"sea_distance_m"`
	View               UnitViewEnum       `json:"view"`
	RowNumber          *int16             `json:"row_number"`
	Amenities          []string           `json:"amenities"`
	Lat                pgtype.Numeric     `json:"lat"`
	Lng                pgtype.Numeric     `json:"lng"`
	ExactAddress       *string            `json:"exact_address"`
	Status             UnitStatusEnum     `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	BufferDays         int16              `json:"buffer_days"`
	AdvanceNoticeHours int32              `json:"advance_notice_hours"`
	MaxAdvanceDays     int32              `json:"max_advance_days"`
	NightlyPrice       *int64             `json:"nightly_price"`
}

type UnitImage struct {
	ID        pgtype.UUID        `json:"id"`
	UnitID    pgtype.UUID        `json:"unit_id"`
	Url       string             `json:"url"`
	AltAr     *string            `json:"alt_ar"`
	AltEn     *string            `json:"alt_en"`
	Sort      int16              `json:"sort"`
	IsCover   bool               `json:"is_cover"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
