// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListPayments = `-- name: AdminListPayments :many
SELECT p.id, p.status, p.amount, p.sender_name, p.sender_number, p.rejection_reason, p.recorded_by,
       p.created_at, p.verified_at, (p.proof_key IS NOT NULL)::boolean AS has_proof, p.proof_type,
       b.id AS booking_id, b.ref, b.status AS booking_status, b.deposit_due, b.paid_total, b.total,
       b.check_in, b.check_out, u.title_ar AS unit_title_ar, u.title_en AS unit_title_en,
       cu.name AS customer_name, cu.phone AS customer_phone
FROM payments p
JOIN bookings b   ON b.id = p.booking_id
JOIN units u      ON u.id = b.unit_id
JOIN customers cu ON cu.id = b.customer_id
WHERE ($1::payment_status_enum IS NULL OR p.status = $1::payment_status_enum)
ORDER BY p.created_at DESC
LIMIT 300
`

type AdminListPaymentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Status          PaymentStatusEnum  `json:"status"`
	Amount          int64              `json:"amount"`
	SenderName      string             `json:"sender_name"`
	SenderNumber    string             `json:"sender_number"`
	RejectionReason *string            `json:"rejection_reason"`
	RecordedBy      string             `json:"recorded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	HasProof        bool               `json:"has_proof"`
	ProofType       *string            `json:"proof_type"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	Ref             string             `json:"ref"`
	BookingStatus   BookingStatusEnum  `json:"booking_status"`
	DepositDue      int64              `json:"deposit_due"`
	PaidTotal       int64              `json:"paid_total"`
	Total           int64              `json:"total"`
	CheckIn         time.Time          `json:"check_in"`
	CheckOut        time.Time          `json:"check_out"`
	UnitTitleAr     string             `json:"unit_title_ar"`
	UnitTitleEn     string             `json:"unit_title_en"`
	CustomerName    string             `json:"customer_name"`
	CustomerPhone   string             `json:"customer_phone"`
}

func (q *Queries) AdminListPayments(ctx context.Context, status NullPaymentStatusEnum) ([]AdminListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, adminListPayments, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPaymentsRow{}
	for rows.Next() {
		var i AdminListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Amount,
			&i.SenderName,
			&i.SenderNumber,
			&i.RejectionReason,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.HasProof,
			&i.ProofType,
			&i.BookingID,
			&i.Ref,
			&i.BookingStatus,
			&i.DepositDue,
			&i.PaidTotal,
			&i.Total,
			&i.CheckIn,
			&i.CheckOut,
			&i.UnitTitleAr,
			&i.UnitTitleEn,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingPayments = `-- name: CountPendingPayments :one
SELECT COUNT(*) FROM payments WHERE status = 'pending'
`

func (q *Queries) CountPendingPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingPaymentsForBooking = `-- name: CountPendingPaymentsForBooking :one
SELECT COUNT(*) FROM payments WHERE booking_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingPaymentsForBooking(ctx context.Context, bookingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPaymentsForBooking, bookingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, status, amount, sender_name, sender_number, proof_key, proof_type, notes, recorded_by, verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10)
RETURNING id, booking_id, method, status, amount, sender_name, sender_number, proof_key, proof_type, rejection_reason, notes, recorded_by, verified_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID    pgtype.UUID        `json:"booking_id"`
	Status       PaymentStatusEnum  `json:"status"`
	Amount       int64              `json:"amount"`
	SenderName   string             `json:"sender_name"`
	SenderNumber string             `json:"sender_number"`
	ProofKey     *string            `json:"proof_key"`
	ProofType    *string            `json:"proof_type"`
	Notes        *string            `json:"notes"`
	RecordedBy   string             `json:"recorded_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.Status,
		arg.Amount,
		arg.SenderName,
		arg.SenderNumber,
		arg.ProofKey,
		arg.ProofType,
		arg.Notes,
		arg.RecordedBy,
		arg.VerifiedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.SenderName,
		&i.SenderNumber,
		&i.ProofKey,
		&i.ProofType,
		&i.RejectionReason,
		&i.Notes,
		&i.RecordedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireHolds = `-- name: ExpireHolds :many
UPDATE bookings SET status = 'expired'
WHERE status = 'pending_payment' AND hold_expires_at < now()
RETURNING ref
`

// Unpaid bookings past their hold: released so others can book the dates.
func (q *Queries) ExpireHolds(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, expireHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ref string
		if err := rows.Scan(&ref); err != nil {
			return nil, err
		}
		items = append(items, ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstapayAccount = `-- name: GetInstapayAccount :one
SELECT address, mobile, holder_name, updated_at FROM instapay_account WHERE id = 1
`

type GetInstapayAccountRow struct {
	Address    string             `json:"address"`
	Mobile     string             `json:"mobile"`
	HolderName string             `json:"holder_name"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInstapayAccount(ctx context.Context) (GetInstapayAccountRow, error) {
	row := q.db.QueryRow(ctx, getInstapayAccount)
	var i GetInstapayAccountRow
	err := row.Scan(
		&i.Address,
		&i.Mobile,
		&i.HolderName,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentProof = `-- name: GetPaymentProof :one
SELECT proof_key, proof_type FROM payments WHERE id = $1
`

type GetPaymentProofRow struct {
	ProofKey  *string `json:"proof_key"`
	ProofType *string `json:"proof_type"`
}

func (q *Queries) GetPaymentProof(ctx context.Context, id pgtype.UUID) (GetPaymentProofRow, error) {
	row := q.db.QueryRow(ctx, getPaymentProof, id)
	var i GetPaymentProofRow
	err := row.Scan(&i.ProofKey, &i.ProofType)
	return i, err
}

const listBookingPayments = `-- name: ListBookingPayments :many
SELECT id, status, amount, sender_name, sender_number, rejection_reason, notes, recorded_by,
       verified_at, created_at, (proof_key IS NOT NULL)::boolean AS has_proof
FROM payments WHERE booking_id = $1 ORDER BY created_at
`

type ListBookingPaymentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Status          PaymentStatusEnum  `json:"status"`
	Amount          int64              `json:"amount"`
	SenderName      string             `json:"sender_name"`
	SenderNumber    string             `json:"sender_number"`
	RejectionReason *string            `json:"rejection_reason"`
	Notes           *string            `json:"notes"`
	RecordedBy      string             `json:"recorded_by"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	HasProof        bool               `json:"has_proof"`
}

func (q *Queries) ListBookingPayments(ctx context.Context, bookingID pgtype.UUID) ([]ListBookingPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listBookingPayments, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingPaymentsRow{}
	for rows.Next() {
		var i ListBookingPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Amount,
			&i.SenderName,
			&i.SenderNumber,
			&i.RejectionReason,
			&i.Notes,
			&i.RecordedBy,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.HasProof,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT id, ref, status, deposit_due, paid_total, payment_rejection_count, hold_expires_at, customer_id
FROM bookings WHERE id = $1 FOR UPDATE
`

type LockBookingRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Ref                   string             `json:"ref"`
	Status                BookingStatusEnum  `json:"status"`
	DepositDue            int64              `json:"deposit_due"`
	PaidTotal             int64              `json:"paid_total"`
	PaymentRejectionCount int16              `json:"payment_rejection_count"`
	HoldExpiresAt         pgtype.Timestamptz `json:"hold_expires_at"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
}

func (q *Queries) LockBooking(ctx context.Context, id pgtype.UUID) (LockBookingRow, error) {
	row := q.db.QueryRow(ctx, lockBooking, id)
	var i LockBookingRow
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Status,
		&i.DepositDue,
		&i.PaidTotal,
		&i.PaymentRejectionCount,
		&i.HoldExpiresAt,
		&i.CustomerID,
	)
	return i, err
}

const lockBookingByRef = `-- name: LockBookingByRef :one
SELECT id, ref, status, deposit_due, paid_total, payment_rejection_count, hold_expires_at, customer_id
FROM bookings WHERE ref = $1 FOR UPDATE
`

type LockBookingByRefRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Ref                   string             `json:"ref"`
	Status                BookingStatusEnum  `json:"status"`
	DepositDue            int64              `json:"deposit_due"`
	PaidTotal             int64              `json:"paid_total"`
	PaymentRejectionCount int16              `json:"payment_rejection_count"`
	HoldExpiresAt         pgtype.Timestamptz `json:"hold_expires_at"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
}

func (q *Queries) LockBookingByRef(ctx context.Context, ref string) (LockBookingByRefRow, error) {
	row := q.db.QueryRow(ctx, lockBookingByRef, ref)
	var i LockBookingByRefRow
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Status,
		&i.DepositDue,
		&i.PaidTotal,
		&i.PaymentRejectionCount,
		&i.HoldExpiresAt,
		&i.CustomerID,
	)
	return i, err
}

const lockPayment = `-- name: LockPayment :one
SELECT id, booking_id, method, status, amount, sender_name, sender_number, proof_key, proof_type, rejection_reason, notes, recorded_by, verified_at, created_at, updated_at FROM payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.SenderName,
		&i.SenderNumber,
		&i.ProofKey,
		&i.ProofType,
		&i.RejectionReason,
		&i.Notes,
		&i.RecordedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectPayment = `-- name: RejectPayment :exec
UPDATE payments SET status = 'rejected', rejection_reason = $1 WHERE id = $2
`

type RejectPaymentParams struct {
	Reason *string     `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RejectPayment(ctx context.Context, arg RejectPaymentParams) error {
	_, err := q.db.Exec(ctx, rejectPayment, arg.Reason, arg.ID)
	return err
}

const setBookingPayment = `-- name: SetBookingPayment :exec
UPDATE bookings
SET status = $1, paid_total = $2, payment_rejection_count = $3,
    hold_expires_at = $4,
    cancelled_at = CASE WHEN $1::booking_status_enum = 'cancelled' THEN now() ELSE cancelled_at END,
    cancel_reason = CASE WHEN $1::booking_status_enum = 'cancelled' THEN $5 ELSE cancel_reason END
WHERE id = $6
`

type SetBookingPaymentParams struct {
	Status                BookingStatusEnum  `json:"status"`
	PaidTotal             int64              `json:"paid_total"`
	PaymentRejectionCount int16              `json:"payment_rejection_count"`
	HoldExpiresAt         pgtype.Timestamptz `json:"hold_expires_at"`
	CancelReason          *string            `json:"cancel_reason"`
	ID                    pgtype.UUID        `json:"id"`
}

func (q *Queries) SetBookingPayment(ctx context.Context, arg SetBookingPaymentParams) error {
	_, err := q.db.Exec(ctx, setBookingPayment,
		arg.Status,
		arg.PaidTotal,
		arg.PaymentRejectionCount,
		arg.HoldExpiresAt,
		arg.CancelReason,
		arg.ID,
	)
	return err
}

const setInstapayAccount = `-- name: SetInstapayAccount :one
UPDATE instapay_account SET address = $1, mobile = $2, holder_name = $3, updated_at = now()
WHERE id = 1
RETURNING address, mobile, holder_name, updated_at
`

type SetInstapayAccountParams struct {
	Address    string `json:"address"`
	Mobile     string `json:"mobile"`
	HolderName string `json:"holder_name"`
}

type SetInstapayAccountRow struct {
	Address    string             `json:"address"`
	Mobile     string             `json:"mobile"`
	HolderName string             `json:"holder_name"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetInstapayAccount(ctx context.Context, arg SetInstapayAccountParams) (SetInstapayAccountRow, error) {
	row := q.db.QueryRow(ctx, setInstapayAccount, arg.Address, arg.Mobile, arg.HolderName)
	var i SetInstapayAccountRow
	err := row.Scan(
		&i.Address,
		&i.Mobile,
		&i.HolderName,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyPayment = `-- name: VerifyPayment :exec
UPDATE payments SET status = 'verified', amount = $1, verified_at = now(), notes = COALESCE($2, notes)
WHERE id = $3
`

type VerifyPaymentParams struct {
	Amount int64       `json:"amount"`
	Notes  *string     `json:"notes"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) VerifyPayment(ctx context.Context, arg VerifyPaymentParams) error {
	_, err := q.db.Exec(ctx, verifyPayment, arg.Amount, arg.Notes, arg.ID)
	return err
}
