// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pricing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPricingUnit = `-- name: GetPricingUnit :one
SELECT id, slug, status, nightly_price, max_guests, buffer_days,
       advance_notice_hours, max_advance_days
FROM units
WHERE ($1::text IS NULL OR slug = $1::text)
  AND ($2::uuid IS NULL OR id = $2::uuid)
  AND (NOT $3::boolean OR status = 'active')
`

type GetPricingUnitParams struct {
	Slug       *string     `json:"slug"`
	ID         pgtype.UUID `json:"id"`
	OnlyActive bool        `json:"only_active"`
}

type GetPricingUnitRow struct {
	ID                 pgtype.UUID    `json:"id"`
	Slug               string         `json:"slug"`
	Status             UnitStatusEnum `json:"status"`
	NightlyPrice       *int64         `json:"nightly_price"`
	MaxGuests          int16          `json:"max_guests"`
	BufferDays         int16          `json:"buffer_days"`
	AdvanceNoticeHours int32          `json:"advance_notice_hours"`
	MaxAdvanceDays     int32          `json:"max_advance_days"`
}

// What pricing needs. Public callers pass only_active so drafts stay hidden.
func (q *Queries) GetPricingUnit(ctx context.Context, arg GetPricingUnitParams) (GetPricingUnitRow, error) {
	row := q.db.QueryRow(ctx, getPricingUnit, arg.Slug, arg.ID, arg.OnlyActive)
	var i GetPricingUnitRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.NightlyPrice,
		&i.MaxGuests,
		&i.BufferDays,
		&i.AdvanceNoticeHours,
		&i.MaxAdvanceDays,
	)
	return i, err
}
