// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: seasons.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const copySeasons = `-- name: CopySeasons :many
INSERT INTO seasons (unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights,
                     allowed_checkin_days, weekend_uplift_pct, priority)
SELECT $1, src.name_ar, src.name_en, src.start_date, src.end_date, src.nightly_price,
       src.min_nights, src.allowed_checkin_days, src.weekend_uplift_pct, src.priority
FROM seasons src WHERE src.unit_id = $2
RETURNING id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at
`

type CopySeasonsParams struct {
	ToUnitID   pgtype.UUID `json:"to_unit_id"`
	FromUnitID pgtype.UUID `json:"from_unit_id"`
}

func (q *Queries) CopySeasons(ctx context.Context, arg CopySeasonsParams) ([]Season, error) {
	rows, err := q.db.Query(ctx, copySeasons, arg.ToUnitID, arg.FromUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.NameAr,
			&i.NameEn,
			&i.StartDate,
			&i.EndDate,
			&i.NightlyPrice,
			&i.MinNights,
			&i.AllowedCheckinDays,
			&i.WeekendUpliftPct,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights,
                     allowed_checkin_days, weekend_uplift_pct, priority)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10)
RETURNING id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at
`

type CreateSeasonParams struct {
	UnitID             pgtype.UUID `json:"unit_id"`
	NameAr             string      `json:"name_ar"`
	NameEn             string      `json:"name_en"`
	StartDate          time.Time   `json:"start_date"`
	EndDate            time.Time   `json:"end_date"`
	NightlyPrice       int64       `json:"nightly_price"`
	MinNights          int16       `json:"min_nights"`
	AllowedCheckinDays []int16     `json:"allowed_checkin_days"`
	WeekendUpliftPct   int16       `json:"weekend_uplift_pct"`
	Priority           int32       `json:"priority"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.UnitID,
		arg.NameAr,
		arg.NameEn,
		arg.StartDate,
		arg.EndDate,
		arg.NightlyPrice,
		arg.MinNights,
		arg.AllowedCheckinDays,
		arg.WeekendUpliftPct,
		arg.Priority,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.NameAr,
		&i.NameEn,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.MinNights,
		&i.AllowedCheckinDays,
		&i.WeekendUpliftPct,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeason = `-- name: DeleteSeason :one
DELETE FROM seasons WHERE id = $1 AND unit_id = $2 RETURNING id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at
`

type DeleteSeasonParams struct {
	ID     pgtype.UUID `json:"id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

func (q *Queries) DeleteSeason(ctx context.Context, arg DeleteSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, deleteSeason, arg.ID, arg.UnitID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.NameAr,
		&i.NameEn,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.MinNights,
		&i.AllowedCheckinDays,
		&i.WeekendUpliftPct,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnitSeasons = `-- name: DeleteUnitSeasons :exec
DELETE FROM seasons WHERE unit_id = $1
`

func (q *Queries) DeleteUnitSeasons(ctx context.Context, unitID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnitSeasons, unitID)
	return err
}

const getSeason = `-- name: GetSeason :one
SELECT id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at FROM seasons WHERE id = $1 AND unit_id = $2
`

type GetSeasonParams struct {
	ID     pgtype.UUID `json:"id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

func (q *Queries) GetSeason(ctx context.Context, arg GetSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, arg.ID, arg.UnitID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.NameAr,
		&i.NameEn,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.MinNights,
		&i.AllowedCheckinDays,
		&i.WeekendUpliftPct,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at FROM seasons WHERE unit_id = $1 ORDER BY start_date, priority DESC
`

func (q *Queries) ListSeasons(ctx context.Context, unitID pgtype.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.NameAr,
			&i.NameEn,
			&i.StartDate,
			&i.EndDate,
			&i.NightlyPrice,
			&i.MinNights,
			&i.AllowedCheckinDays,
			&i.WeekendUpliftPct,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE seasons
SET name_ar = $1, name_en = $2, start_date = $3, end_date = $4,
    nightly_price = $5, min_nights = $6,
    allowed_checkin_days = $7, weekend_uplift_pct = $8,
    priority = $9
WHERE id = $10 AND unit_id = $11
RETURNING id, unit_id, name_ar, name_en, start_date, end_date, nightly_price, min_nights, allowed_checkin_days, weekend_uplift_pct, priority, created_at, updated_at
`

type UpdateSeasonParams struct {
	NameAr             string      `json:"name_ar"`
	NameEn             string      `json:"name_en"`
	StartDate          time.Time   `json:"start_date"`
	EndDate            time.Time   `json:"end_date"`
	NightlyPrice       int64       `json:"nightly_price"`
	MinNights          int16       `json:"min_nights"`
	AllowedCheckinDays []int16     `json:"allowed_checkin_days"`
	WeekendUpliftPct   int16       `json:"weekend_uplift_pct"`
	Priority           int32       `json:"priority"`
	ID                 pgtype.UUID `json:"id"`
	UnitID             pgtype.UUID `json:"unit_id"`
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.NameAr,
		arg.NameEn,
		arg.StartDate,
		arg.EndDate,
		arg.NightlyPrice,
		arg.MinNights,
		arg.AllowedCheckinDays,
		arg.WeekendUpliftPct,
		arg.Priority,
		arg.ID,
		arg.UnitID,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.NameAr,
		&i.NameEn,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.MinNights,
		&i.AllowedCheckinDays,
		&i.WeekendUpliftPct,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
