// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchUnits = `-- name: CountSearchUnits :one
SELECT COUNT(*)
FROM units u
JOIN compounds c ON c.id = u.compound_id
JOIN areas     a ON a.id = c.area_id
WHERE u.status = 'active'
  AND ($1::text     IS NULL OR a.slug = $1::text)
  AND ($2::text IS NULL OR c.slug = $2::text)
  AND ($3::unit_type_enum IS NULL OR u.type = $3::unit_type_enum)
  AND ($4::unit_view_enum IS NULL OR u.view = $4::unit_view_enum)
  AND ($5::int         IS NULL OR u.max_guests >= $5::int)
  AND ($6::int       IS NULL OR u.bedrooms   >= $6::int)
  AND ($7::int IS NULL OR u.sea_distance_m <= $7::int)
`

type CountSearchUnitsParams struct {
	AreaSlug       *string          `json:"area_slug"`
	CompoundSlug   *string          `json:"compound_slug"`
	UnitType       NullUnitTypeEnum `json:"unit_type"`
	UnitView       NullUnitViewEnum `json:"unit_view"`
	Guests         *int32           `json:"guests"`
	Bedrooms       *int32           `json:"bedrooms"`
	MaxSeaDistance *int32           `json:"max_sea_distance"`
}

func (q *Queries) CountSearchUnits(ctx context.Context, arg CountSearchUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUnits,
		arg.AreaSlug,
		arg.CompoundSlug,
		arg.UnitType,
		arg.UnitView,
		arg.Guests,
		arg.Bedrooms,
		arg.MaxSeaDistance,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublicUnitBySlug = `-- name: GetPublicUnitBySlug :one
SELECT
  u.id, u.compound_id, u.slug,
  u.title_ar, u.title_en, u.description_ar, u.description_en,
  u.house_rules_ar, u.house_rules_en,
  u.type, u.bedrooms, u.bathrooms, u.base_guests, u.max_guests,
  u.area_sqm, u.floor, u.sea_distance_m, u.view, u.row_number,
  u.amenities, u.lat, u.lng, u.status, u.created_at, u.updated_at,
  c.id AS compound_id_out, c.slug AS compound_slug, c.name_ar AS compound_name_ar, c.name_en AS compound_name_en,
  a.id AS area_id, a.slug AS area_slug, a.name_ar AS area_name_ar, a.name_en AS area_name_en
FROM units u
JOIN compounds c ON c.id = u.compound_id
JOIN areas     a ON a.id = c.area_id
WHERE u.slug = $1 AND u.status = 'active'
`

type GetPublicUnitBySlugRow struct {
	ID             pgtype.UUID        `json:"id"`
	CompoundID     pgtype.UUID        `json:"compound_id"`
	Slug           string             `json:"slug"`
	TitleAr        string             `json:"title_ar"`
	TitleEn        string             `json:"title_en"`
	DescriptionAr  string             `json:"description_ar"`
	DescriptionEn  string             `json:"description_en"`
	HouseRulesAr   *string            `json:"house_rules_ar"`
	HouseRulesEn   *string            `json:"house_rules_en"`
	Type           UnitTypeEnum       `json:"type"`
	Bedrooms       int16              `json:"bedrooms"`
	Bathrooms      int16              `json:"bathrooms"`
	BaseGuests     int16              `json:"base_guests"`
	MaxGuests      int16              `json:"max_guests"`
	AreaSqm        *int32             `json:"area_sqm"`
	Floor          *int16             `json:"floor"`
	SeaDistanceM   int32              `json:"sea_distance_m"`
	View           UnitViewEnum       `json:"view"`
	RowNumber      *int16             `json:"row_number"`
	Amenities      []string           `json:"amenities"`
	Lat            pgtype.Numeric     `json:"lat"`
	Lng            pgtype.Numeric     `json:"lng"`
	Status         UnitStatusEnum     `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompoundIDOut  pgtype.UUID        `json:"compound_id_out"`
	CompoundSlug   string             `json:"compound_slug"`
	CompoundNameAr string             `json:"compound_name_ar"`
	CompoundNameEn string             `json:"compound_name_en"`
	AreaID         pgtype.UUID        `json:"area_id"`
	AreaSlug       string             `json:"area_slug"`
	AreaNameAr     string             `json:"area_name_ar"`
	AreaNameEn     string             `json:"area_name_en"`
}

// exact_address is deliberately absent: it must never reach public callers.
func (q *Queries) GetPublicUnitBySlug(ctx context.Context, slug string) (GetPublicUnitBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicUnitBySlug, slug)
	var i GetPublicUnitBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CompoundID,
		&i.Slug,
		&i.TitleAr,
		&i.TitleEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.HouseRulesAr,
		&i.HouseRulesEn,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.BaseGuests,
		&i.MaxGuests,
		&i.AreaSqm,
		&i.Floor,
		&i.SeaDistanceM,
		&i.View,
		&i.RowNumber,
		&i.Amenities,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompoundIDOut,
		&i.CompoundSlug,
		&i.CompoundNameAr,
		&i.CompoundNameEn,
		&i.AreaID,
		&i.AreaSlug,
		&i.AreaNameAr,
		&i.AreaNameEn,
	)
	return i, err
}

const listImagesByUnitID = `-- name: ListImagesByUnitID :many
SELECT id, unit_id, url, alt_ar, alt_en, sort, is_cover
FROM unit_images
WHERE unit_id = $1
ORDER BY is_cover DESC, sort ASC, created_at ASC
`

type ListImagesByUnitIDRow struct {
	ID      pgtype.UUID `json:"id"`
	UnitID  pgtype.UUID `json:"unit_id"`
	Url     string      `json:"url"`
	AltAr   *string     `json:"alt_ar"`
	AltEn   *string     `json:"alt_en"`
	Sort    int16       `json:"sort"`
	IsCover bool        `json:"is_cover"`
}

func (q *Queries) ListImagesByUnitID(ctx context.Context, unitID pgtype.UUID) ([]ListImagesByUnitIDRow, error) {
	rows, err := q.db.Query(ctx, listImagesByUnitID, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesByUnitIDRow{}
	for rows.Next() {
		var i ListImagesByUnitIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Url,
			&i.AltAr,
			&i.AltEn,
			&i.Sort,
			&i.IsCover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUnits = `-- name: SearchUnits :many
SELECT
  u.id, u.owner_id, u.compound_id, u.slug,
  u.title_ar, u.title_en, u.type, u.bedrooms, u.bathrooms,
  u.base_guests, u.max_guests, u.area_sqm, u.floor,
  u.sea_distance_m, u.view, u.status, u.created_at,
  c.slug AS compound_slug, c.name_en AS compound_name_en,
  a.slug AS area_slug,     a.name_en AS area_name_en
FROM units u
JOIN compounds c ON c.id = u.compound_id
JOIN areas     a ON a.id = c.area_id
WHERE u.status = 'active'
  AND ($1::text     IS NULL OR a.slug = $1::text)
  AND ($2::text IS NULL OR c.slug = $2::text)
  AND ($3::unit_type_enum IS NULL OR u.type = $3::unit_type_enum)
  AND ($4::unit_view_enum IS NULL OR u.view = $4::unit_view_enum)
  AND ($5::int         IS NULL OR u.max_guests >= $5::int)
  AND ($6::int       IS NULL OR u.bedrooms   >= $6::int)
  AND ($7::int IS NULL OR u.sea_distance_m <= $7::int)
ORDER BY
  CASE WHEN $8::text = 'sea_distance_asc' THEN u.sea_distance_m END ASC NULLS LAST,
  CASE WHEN $8::text = 'bedrooms_desc'    THEN u.bedrooms       END DESC NULLS LAST,
  u.created_at DESC
LIMIT $10 OFFSET $9
`

type SearchUnitsParams struct {
	AreaSlug       *string          `json:"area_slug"`
	CompoundSlug   *string          `json:"compound_slug"`
	UnitType       NullUnitTypeEnum `json:"unit_type"`
	UnitView       NullUnitViewEnum `json:"unit_view"`
	Guests         *int32           `json:"guests"`
	Bedrooms       *int32           `json:"bedrooms"`
	MaxSeaDistance *int32           `json:"max_sea_distance"`
	SortKey        string           `json:"sort_key"`
	PageOffset     int32            `json:"page_offset"`
	PageLimit      int32            `json:"page_limit"`
}

type SearchUnitsRow struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	CompoundID     pgtype.UUID        `json:"compound_id"`
	Slug           string             `json:"slug"`
	TitleAr        string             `json:"title_ar"`
	TitleEn        string             `json:"title_en"`
	Type           UnitTypeEnum       `json:"type"`
	Bedrooms       int16              `json:"bedrooms"`
	Bathrooms      int16              `json:"bathrooms"`
	BaseGuests     int16              `json:"base_guests"`
	MaxGuests      int16              `json:"max_guests"`
	AreaSqm        *int32             `json:"area_sqm"`
	Floor          *int16             `json:"floor"`
	SeaDistanceM   int32              `json:"sea_distance_m"`
	View           UnitViewEnum       `json:"view"`
	Status         UnitStatusEnum     `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompoundSlug   string             `json:"compound_slug"`
	CompoundNameEn string             `json:"compound_name_en"`
	AreaSlug       string             `json:"area_slug"`
	AreaNameEn     string             `json:"area_name_en"`
}

func (q *Queries) SearchUnits(ctx context.Context, arg SearchUnitsParams) ([]SearchUnitsRow, error) {
	rows, err := q.db.Query(ctx, searchUnits,
		arg.AreaSlug,
		arg.CompoundSlug,
		arg.UnitType,
		arg.UnitView,
		arg.Guests,
		arg.Bedrooms,
		arg.MaxSeaDistance,
		arg.SortKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUnitsRow{}
	for rows.Next() {
		var i SearchUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CompoundID,
			&i.Slug,
			&i.TitleAr,
			&i.TitleEn,
			&i.Type,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.BaseGuests,
			&i.MaxGuests,
			&i.AreaSqm,
			&i.Floor,
			&i.SeaDistanceM,
			&i.View,
			&i.Status,
			&i.CreatedAt,
			&i.CompoundSlug,
			&i.CompoundNameEn,
			&i.AreaSlug,
			&i.AreaNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
